{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "core",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v145.1.jar",
          "url": "core-v145.1.jar",
          "size": 4836435,
          "sha512": "cc11f21e1cc795048875bae5ffaf5bd76cd1d5c8bdb38b547a2d9e121b399ed23728aec9a6e309f4fe755f6e58bcf2bca5d33078ba3ca69ba5504cbd8f3c6157",
          "sha256": "47e9d5a5b08b72a2ba1e63f5572d3dfae92986c658ab2ebab132fe41cc5d6eb4",
          "sha1": "7633c6aceca7f53e323d704984ce795f8a2a9017",
          "md5": "981f85c568543aa86166d26a0beebbb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v145.1.jar",
          "url": "core-v145.1.jar",
          "size": 4836435,
          "sha512": "cc11f21e1cc795048875bae5ffaf5bd76cd1d5c8bdb38b547a2d9e121b399ed23728aec9a6e309f4fe755f6e58bcf2bca5d33078ba3ca69ba5504cbd8f3c6157",
          "sha256": "47e9d5a5b08b72a2ba1e63f5572d3dfae92986c658ab2ebab132fe41cc5d6eb4",
          "sha1": "7633c6aceca7f53e323d704984ce795f8a2a9017",
          "md5": "981f85c568543aa86166d26a0beebbb4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v145.1-sources.jar",
          "url": "core-v145.1-sources.jar",
          "size": 1291504,
          "sha512": "7158949b59e8f360bab95cc621e9bc64b009728021bfd2cf996e897f7dce04cfebce9fe7c9bb896c1084f1a770b45dc58374badd2903b64777bbc321d64ad311",
          "sha256": "a1db9bba22da584a76b4ff980def0a337d42ef9ffcf1b4e4572b7a097bb6c4c7",
          "sha1": "38f2c829fafc2e883f1bc187e19a3f3ef89dda36",
          "md5": "2829b4dd5f08dba7452ceb5e9b6912f0"
        }
      ]
    }
  ]
}
