{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "discord",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "discord-v145.1.jar",
          "url": "discord-v145.1.jar",
          "size": 15193,
          "sha512": "0e05446c79fdfd630ded04707b96e916644b12d4646b6b4065e04a8d285a28131585e365fa124b45c1dc89ef66c4ec596e3ab7005689e0c08f7b209c58ea77ea",
          "sha256": "a7cec1a0edcf52b4db74cfe676d8010fcf03cb0cd7f6ab59272ba060f031d790",
          "sha1": "1c86515515389efe1d292c16b5b4fff3d8afa6a9",
          "md5": "d0eb5a2f2f4c69840308f9b037cdfebb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-v145.1.jar",
          "url": "discord-v145.1.jar",
          "size": 15193,
          "sha512": "0e05446c79fdfd630ded04707b96e916644b12d4646b6b4065e04a8d285a28131585e365fa124b45c1dc89ef66c4ec596e3ab7005689e0c08f7b209c58ea77ea",
          "sha256": "a7cec1a0edcf52b4db74cfe676d8010fcf03cb0cd7f6ab59272ba060f031d790",
          "sha1": "1c86515515389efe1d292c16b5b4fff3d8afa6a9",
          "md5": "d0eb5a2f2f4c69840308f9b037cdfebb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-v145.1-sources.jar",
          "url": "discord-v145.1-sources.jar",
          "size": 4401,
          "sha512": "135bd95ca452cfc8a545c9521b730aec7799f46dd2fe920d819273212c15a5972d2fee584e7e56e12390f282c67677b587ae64c38b70f5b3da050f6b34eec84b",
          "sha256": "42dad5876c76ed27bb94852d1554e6e6d74a991ff6c74f3db1cff60439c57220",
          "sha1": "574baf95b16aed5eb6619d9de8bdc3e442978bf6",
          "md5": "048cde400fa12ee8563b17aec6f1eedf"
        }
      ]
    }
  ]
}
