{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-v145.jar",
          "url": "natives-v145.jar",
          "size": 261,
          "sha512": "85cead96aab8e5810aefe8000abaefd9dc8bdcef7a9e691ff5058acf04a773d6d3ab3e745807fa29212bfc5aec509f226522b86bdf8dced944c91df6d01e00ce",
          "sha256": "9d94fa592d06d563a0fc3d94ac275579923a90cd5bf667027f434987f1c85677",
          "sha1": "d32de7e4390df31fffb21e4639007601deb3b547",
          "md5": "c9ad5b34ee2c0b18d27787c6f03c865d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-v145.jar",
          "url": "natives-v145.jar",
          "size": 261,
          "sha512": "85cead96aab8e5810aefe8000abaefd9dc8bdcef7a9e691ff5058acf04a773d6d3ab3e745807fa29212bfc5aec509f226522b86bdf8dced944c91df6d01e00ce",
          "sha256": "9d94fa592d06d563a0fc3d94ac275579923a90cd5bf667027f434987f1c85677",
          "sha1": "d32de7e4390df31fffb21e4639007601deb3b547",
          "md5": "c9ad5b34ee2c0b18d27787c6f03c865d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-v145-sources.jar",
          "url": "natives-v145-sources.jar",
          "size": 261,
          "sha512": "85cead96aab8e5810aefe8000abaefd9dc8bdcef7a9e691ff5058acf04a773d6d3ab3e745807fa29212bfc5aec509f226522b86bdf8dced944c91df6d01e00ce",
          "sha256": "9d94fa592d06d563a0fc3d94ac275579923a90cd5bf667027f434987f1c85677",
          "sha1": "d32de7e4390df31fffb21e4639007601deb3b547",
          "md5": "c9ad5b34ee2c0b18d27787c6f03c865d"
        }
      ]
    }
  ]
}
