{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-android",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-android-v145.1.jar",
          "url": "natives-android-v145.1.jar",
          "size": 1119476,
          "sha512": "d200ca96d0347d4bbb20ecf6958ba889d1da1f18831f9ff5d8d1e4da553832959eab8e7557f4a22063a57af9c35c8bb7da83d45e84ff9f2cb559c5d97507ea52",
          "sha256": "b06abb37ffc3d238b332f80a62c4a699b20a4dab824392c4751ae06de97fc82a",
          "sha1": "9ef37dfa33505811fcbb9c8be8cf3684afe08c33",
          "md5": "0c50941713e07db19263bb6304f405d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-android-v145.1.jar",
          "url": "natives-android-v145.1.jar",
          "size": 1119476,
          "sha512": "d200ca96d0347d4bbb20ecf6958ba889d1da1f18831f9ff5d8d1e4da553832959eab8e7557f4a22063a57af9c35c8bb7da83d45e84ff9f2cb559c5d97507ea52",
          "sha256": "b06abb37ffc3d238b332f80a62c4a699b20a4dab824392c4751ae06de97fc82a",
          "sha1": "9ef37dfa33505811fcbb9c8be8cf3684afe08c33",
          "md5": "0c50941713e07db19263bb6304f405d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-android-v145.1-sources.jar",
          "url": "natives-android-v145.1-sources.jar",
          "size": 1119476,
          "sha512": "8da5b0c85c3eb6e5b58c7275afe23b43ab576b139d601bd5f05e330e6954b2b7ef9fb3688f641edaf50a7c5ca07454742e59c7ce225de31982c6632980501b91",
          "sha256": "030eebc3142c62938105f034cb68212171da40fca009b7ea24e456532155bf49",
          "sha1": "bf7d2cccbdf9bf5823bd75f593fa2731c266db65",
          "md5": "56a42e302ed44013cd1e8de847ff1a40"
        }
      ]
    }
  ]
}
