{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v146",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v146.jar",
          "url": "backends-v146.jar",
          "size": 261,
          "sha512": "5e29a9aac9841d3b0381c0967956733df85174584bed01b2ebb0129832c6d967c542824067181aa1768ed75a95a56e57eb260e8713579eacdace151242b888ed",
          "sha256": "cde2c79833c0f324de39aa89523346e5cbd083d9733129a181d7d9d5765a1d73",
          "sha1": "2bb01fd647894a43205e59f1e9e9a3a369902e17",
          "md5": "a4151cc73bea69d4cb8f03384082f657"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v146.jar",
          "url": "backends-v146.jar",
          "size": 261,
          "sha512": "5e29a9aac9841d3b0381c0967956733df85174584bed01b2ebb0129832c6d967c542824067181aa1768ed75a95a56e57eb260e8713579eacdace151242b888ed",
          "sha256": "cde2c79833c0f324de39aa89523346e5cbd083d9733129a181d7d9d5765a1d73",
          "sha1": "2bb01fd647894a43205e59f1e9e9a3a369902e17",
          "md5": "a4151cc73bea69d4cb8f03384082f657"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v146-sources.jar",
          "url": "backends-v146-sources.jar",
          "size": 261,
          "sha512": "5e29a9aac9841d3b0381c0967956733df85174584bed01b2ebb0129832c6d967c542824067181aa1768ed75a95a56e57eb260e8713579eacdace151242b888ed",
          "sha256": "cde2c79833c0f324de39aa89523346e5cbd083d9733129a181d7d9d5765a1d73",
          "sha1": "2bb01fd647894a43205e59f1e9e9a3a369902e17",
          "md5": "a4151cc73bea69d4cb8f03384082f657"
        }
      ]
    }
  ]
}
