{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken",
    "module": "jabel",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jabel-0.9.0.jar",
          "url": "jabel-0.9.0.jar",
          "size": 2796,
          "sha512": "1591d80e75db4177f9a602faf0c461709a6ff72ac0410588f8eb1225f8ebe601ca7c1788b5cfaa32d6b6e589ba655d98c50324a3bdf13220a41ad5cc299c8d90",
          "sha256": "47c6297191061ca84a8d0b28b2f3b9f1b44f9410dbf287c26ce4787744975feb",
          "sha1": "fcb054d4d745a77f06e21383043330b1f6873a52",
          "md5": "5adeca8881c3a38c42641bcbb282aa3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jabel-0.9.0.jar",
          "url": "jabel-0.9.0.jar",
          "size": 2796,
          "sha512": "1591d80e75db4177f9a602faf0c461709a6ff72ac0410588f8eb1225f8ebe601ca7c1788b5cfaa32d6b6e589ba655d98c50324a3bdf13220a41ad5cc299c8d90",
          "sha256": "47c6297191061ca84a8d0b28b2f3b9f1b44f9410dbf287c26ce4787744975feb",
          "sha1": "fcb054d4d745a77f06e21383043330b1f6873a52",
          "md5": "5adeca8881c3a38c42641bcbb282aa3e"
        }
      ]
    }
  ]
}
