{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "profiling",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "profiling-v145.jar",
          "url": "profiling-v145.jar",
          "size": 23501,
          "sha512": "cd243ca6e8140777db0685d46e34aa3be50afb34fdf336dc7ea7eb846aa0b662d2c60d89a4b0f238da4b0a32ed2d06dca3aba41b5df412e0bed9db50177b48ea",
          "sha256": "da422e18fcb6ccbee21b8d54fe2533608673d05e1fdd8de4ad2bd39bc0683bc6",
          "sha1": "907ef883304328c6232761e7ffbb4cc02e37184f",
          "md5": "bb69778e2fb02e5a4ed7fc0b2752972f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profiling-v145.jar",
          "url": "profiling-v145.jar",
          "size": 23501,
          "sha512": "cd243ca6e8140777db0685d46e34aa3be50afb34fdf336dc7ea7eb846aa0b662d2c60d89a4b0f238da4b0a32ed2d06dca3aba41b5df412e0bed9db50177b48ea",
          "sha256": "da422e18fcb6ccbee21b8d54fe2533608673d05e1fdd8de4ad2bd39bc0683bc6",
          "sha1": "907ef883304328c6232761e7ffbb4cc02e37184f",
          "md5": "bb69778e2fb02e5a4ed7fc0b2752972f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profiling-v145-sources.jar",
          "url": "profiling-v145-sources.jar",
          "size": 11159,
          "sha512": "d3529126de0c89ca3e4f56e5db7b08439d6ba4a719627db50db408aebb019c575fffe6a2578ae79e2651c7130f6d54d1b0121f8e065a02c7319406c755ee4b00",
          "sha256": "327dac66c320eb6478cc07708035c0b98d86428f7cc22e669ebcd16409a87e64",
          "sha1": "8242b3a606418da3ed6ddabb7caccf38a1172b9a",
          "md5": "b51feb0768b72eef6f9eadc157623027"
        }
      ]
    }
  ]
}
