{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-android",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-android-v145.1.jar",
          "url": "backend-android-v145.1.jar",
          "size": 68308,
          "sha512": "e3ec8275685cc7495e53064072a3dbbb0495b2b2e9cbd611cce8dc17bdb9f6f4bb1e80580cc20b4ee633b10abe7ddbee690f91c43d8317dee278f1acd9077a6e",
          "sha256": "a67580622e0864c453661a23855f32ca3b86a94d8f3099fbd844c6fb55d3c286",
          "sha1": "c1947bb2a127703af4a351d695022a13fd4c52db",
          "md5": "4e0e3ae9b659e5a3001c6e2f73c0e5b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-android-v145.1.jar",
          "url": "backend-android-v145.1.jar",
          "size": 68308,
          "sha512": "e3ec8275685cc7495e53064072a3dbbb0495b2b2e9cbd611cce8dc17bdb9f6f4bb1e80580cc20b4ee633b10abe7ddbee690f91c43d8317dee278f1acd9077a6e",
          "sha256": "a67580622e0864c453661a23855f32ca3b86a94d8f3099fbd844c6fb55d3c286",
          "sha1": "c1947bb2a127703af4a351d695022a13fd4c52db",
          "md5": "4e0e3ae9b659e5a3001c6e2f73c0e5b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-android-v145.1-sources.jar",
          "url": "backend-android-v145.1-sources.jar",
          "size": 36097,
          "sha512": "fe09a0fa94e0f24c05b4e804284045fce67d323da43ae29b7e640be34950f766f77db594487081813f315a1302483a9dc189d111fdeee2570df673bc09292db7",
          "sha256": "668bbf69f3696d09fa6527c01bee501b56fc7738c82320470fc7125b81a60536",
          "sha1": "25d9bc83228aafec1b7ca5ed9587408d2727a053",
          "md5": "8410bfd883f2708cc98dd23e2424a924"
        }
      ]
    }
  ]
}
