{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "tiled",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiled-v145.jar",
          "url": "tiled-v145.jar",
          "size": 42985,
          "sha512": "55825ec16209fa9218ac23e9bddf75e84f9bd4d2d62a87869c85621ae938cd215b2e7a6d6fdb8a7ea4514a2b159dd49cfa80f9dc3e27bc8f6c8649824431dbea",
          "sha256": "af192587bf9db819cb5f47beb08e30388a6b215e13afffe6fd46d97cd1de129b",
          "sha1": "44b6b86f0b815c474aa3860ffffbfe640ff3880d",
          "md5": "f71197c823e288ae7ae5b44060f1166a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v145.jar",
          "url": "tiled-v145.jar",
          "size": 42985,
          "sha512": "55825ec16209fa9218ac23e9bddf75e84f9bd4d2d62a87869c85621ae938cd215b2e7a6d6fdb8a7ea4514a2b159dd49cfa80f9dc3e27bc8f6c8649824431dbea",
          "sha256": "af192587bf9db819cb5f47beb08e30388a6b215e13afffe6fd46d97cd1de129b",
          "sha1": "44b6b86f0b815c474aa3860ffffbfe640ff3880d",
          "md5": "f71197c823e288ae7ae5b44060f1166a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v145-sources.jar",
          "url": "tiled-v145-sources.jar",
          "size": 23367,
          "sha512": "5b555fb348c97722b27216cf8b284fa3536dfc8b7b234d8d5367555babd3cf35290a39e2c4fc60031b455139f70471069bc8b0e25f51ea42ea4aa3e1fe0015ba",
          "sha256": "819ae676aae7c47761525942adbb938d010e9707fde49f75a0503262855de43e",
          "sha1": "4a60553a57131102e19b4ada1332f182710a8784",
          "md5": "05161e106f36e20711a1d41fa8aaa54f"
        }
      ]
    }
  ]
}
