{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v145.jar",
          "url": "backend-sdl-v145.jar",
          "size": 3750876,
          "sha512": "08e8775a17244346947cb4bf7b7766236aa11d632ad6cadae761ce7e9f3358e237217b68a929a53edf5caf46ccc8da7568101b9f44d8abf8ee6c16c6e7c1b5aa",
          "sha256": "264a4bf7ce56488f48ac1178e23bddbd00899a62084cdb56e817b0e8221740b6",
          "sha1": "65d5fcd33a6b0cb953ed933bfa8b24e1824000c9",
          "md5": "e4f6d5c72fba5c38e080b35c1e8837c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v145.jar",
          "url": "backend-sdl-v145.jar",
          "size": 3750876,
          "sha512": "08e8775a17244346947cb4bf7b7766236aa11d632ad6cadae761ce7e9f3358e237217b68a929a53edf5caf46ccc8da7568101b9f44d8abf8ee6c16c6e7c1b5aa",
          "sha256": "264a4bf7ce56488f48ac1178e23bddbd00899a62084cdb56e817b0e8221740b6",
          "sha1": "65d5fcd33a6b0cb953ed933bfa8b24e1824000c9",
          "md5": "e4f6d5c72fba5c38e080b35c1e8837c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v145-sources.jar",
          "url": "backend-sdl-v145-sources.jar",
          "size": 3731433,
          "sha512": "d5d5f21fac0d7fcd078746f888928ba07fb724faff19ff2b4f064ac6aa70d1ea33ca16eebec697437fdbaf2307e7f75e3a1441394b0c7d8409ae03c511620c62",
          "sha256": "2e378852e9709b2bbb35503068a250a7d80d1ec1244660402af0b457afb53046",
          "sha1": "9daf2d28a78ad7f3aa0dd25b79ff5230d8796f55",
          "md5": "556266cd7c1666da38189e5a9e098d8e"
        }
      ]
    }
  ]
}
