{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken",
    "module": "backend-sdl",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v145.jar",
          "url": "backend-sdl-v145.jar",
          "size": 3750876,
          "sha512": "86b7a3d23cc2f9c9c6f5c3c22215c5bc8b50e1649e6c5377dfbae35fa3407d5229b12f08cf0fdf6ef036495d689d5a17452a7d7cad56e1ccd09eb61572879bae",
          "sha256": "47c15cc5f56868b1d2c4b85fb2b8b723cf27edd83c3c875cf23b634eb3f44b5d",
          "sha1": "ea1fbd39797d1600196df058a527072ed619a333",
          "md5": "ef3b013111ffdb153cf15925d138ab47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v145.jar",
          "url": "backend-sdl-v145.jar",
          "size": 3750876,
          "sha512": "86b7a3d23cc2f9c9c6f5c3c22215c5bc8b50e1649e6c5377dfbae35fa3407d5229b12f08cf0fdf6ef036495d689d5a17452a7d7cad56e1ccd09eb61572879bae",
          "sha256": "47c15cc5f56868b1d2c4b85fb2b8b723cf27edd83c3c875cf23b634eb3f44b5d",
          "sha1": "ea1fbd39797d1600196df058a527072ed619a333",
          "md5": "ef3b013111ffdb153cf15925d138ab47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v145-sources.jar",
          "url": "backend-sdl-v145-sources.jar",
          "size": 3731433,
          "sha512": "422255a45f18b31adbe8802f0a92c4f8196b5d36178e2c3f8cb8294403e2ece6fcaadecf2d93ad309062c71df5c66cd97dbd91cea24b829b5c4e5021fd4008e5",
          "sha256": "feaaba1485eccd55dd3ce6dced91ae22cbf45a3b8c4309fe93e1f7388f09cef6",
          "sha1": "cd77fd447cee80395cdfad08e963d2cd8951262e",
          "md5": "88603e117aa3983ef064271d6e1f390e"
        }
      ]
    }
  ]
}
