{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-desktop",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-desktop-v145.1.jar",
          "url": "natives-desktop-v145.1.jar",
          "size": 1687632,
          "sha512": "33380bf20c9cd63e0ddb374fde3590605552713c955b34ac3e374b56ccb82a8a6ca6e2c1d9264354f488bf1ea558ad15a9d37768a1c5eab69d102e73773d703a",
          "sha256": "c01e2731e99ff4ff548ea13e3fba2ebd3d6eb08316db6ca64413584faac7ea4b",
          "sha1": "a373f6a66a27849c1336aa1ea1e4d8e5f87a1ef7",
          "md5": "c934407600214e7e8567343ccdfd46ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-desktop-v145.1.jar",
          "url": "natives-desktop-v145.1.jar",
          "size": 1687632,
          "sha512": "33380bf20c9cd63e0ddb374fde3590605552713c955b34ac3e374b56ccb82a8a6ca6e2c1d9264354f488bf1ea558ad15a9d37768a1c5eab69d102e73773d703a",
          "sha256": "c01e2731e99ff4ff548ea13e3fba2ebd3d6eb08316db6ca64413584faac7ea4b",
          "sha1": "a373f6a66a27849c1336aa1ea1e4d8e5f87a1ef7",
          "md5": "c934407600214e7e8567343ccdfd46ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-desktop-v145.1-sources.jar",
          "url": "natives-desktop-v145.1-sources.jar",
          "size": 1687632,
          "sha512": "c960138cfa3e7465f0bd153bd9b5ce3e897ad903c03a0c53333daf44300bbe872a200d7d16aee98ab7b57f65c922f28da87ad200a478c1e3b311d2f30875d56a",
          "sha256": "391a834337cd6f380cacd6bd454489b328713a01c7e2fb8a257171c335aa1901",
          "sha1": "f17dd1fd451920c2416e596af04fc1d004657204",
          "md5": "debd6ff3e0cefb8bd88d1a65d9dfb4f0"
        }
      ]
    }
  ]
}
