{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-ios",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v145.1.jar",
          "url": "natives-box2d-ios-v145.1.jar",
          "size": 2384392,
          "sha512": "17acb77a007655ae4708ae2f741dde4fad95c0978f7d1a10938891163b57c125dd02330f464986b861b160f4ed83159a6589fcc320b8132ecd0f03e21b913751",
          "sha256": "07fc1fce6deb8610b582152f194d99e94da4c813d4868c5d1b1c37c461ff1cf8",
          "sha1": "5240f43024b393d56e8fe29a7b3e2a343ac833b0",
          "md5": "00acea81751b84898c1103b4d7c92e85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v145.1.jar",
          "url": "natives-box2d-ios-v145.1.jar",
          "size": 2384392,
          "sha512": "17acb77a007655ae4708ae2f741dde4fad95c0978f7d1a10938891163b57c125dd02330f464986b861b160f4ed83159a6589fcc320b8132ecd0f03e21b913751",
          "sha256": "07fc1fce6deb8610b582152f194d99e94da4c813d4868c5d1b1c37c461ff1cf8",
          "sha1": "5240f43024b393d56e8fe29a7b3e2a343ac833b0",
          "md5": "00acea81751b84898c1103b4d7c92e85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v145.1-sources.jar",
          "url": "natives-box2d-ios-v145.1-sources.jar",
          "size": 2384392,
          "sha512": "690caf68f34ebcac3f5316a2ecd0c9b8eb0ec8dae5e4be35d4c791baaeeba3b8e522b97cb0bbf79ad958c2f35ef6a194a4c757bc67fc9b699ece4bb07666ca76",
          "sha256": "31a2f3f6bcd3edee82e50301a5b3d88f10b27ef946e1c7c0b88e27bd0b0068d8",
          "sha1": "d0eb6e1a34016152c5e838b8b548d061d6fff279",
          "md5": "b28cfde77dc6b7fa623be3a1f59e5b40"
        }
      ]
    }
  ]
}
