{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v145.1.jar",
          "url": "backends-v145.1.jar",
          "size": 261,
          "sha512": "32c87cc72ee005f853faa8fef86335be25542eed85b6a0eb19e6e636e42de428394eb50024f73da40b16bcc079ddd902efff3076373ec595b1d09a7a1642802a",
          "sha256": "86fe38ec0094e399dc1d32c8e8bb40d8dbe424a6c8d9c53af8fed375200737d9",
          "sha1": "1931fc7cea96cb20cb3924f80756782014a628cf",
          "md5": "5008798857671eecb81da6a17cab8588"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v145.1.jar",
          "url": "backends-v145.1.jar",
          "size": 261,
          "sha512": "32c87cc72ee005f853faa8fef86335be25542eed85b6a0eb19e6e636e42de428394eb50024f73da40b16bcc079ddd902efff3076373ec595b1d09a7a1642802a",
          "sha256": "86fe38ec0094e399dc1d32c8e8bb40d8dbe424a6c8d9c53af8fed375200737d9",
          "sha1": "1931fc7cea96cb20cb3924f80756782014a628cf",
          "md5": "5008798857671eecb81da6a17cab8588"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v145.1-sources.jar",
          "url": "backends-v145.1-sources.jar",
          "size": 261,
          "sha512": "32c87cc72ee005f853faa8fef86335be25542eed85b6a0eb19e6e636e42de428394eb50024f73da40b16bcc079ddd902efff3076373ec595b1d09a7a1642802a",
          "sha256": "86fe38ec0094e399dc1d32c8e8bb40d8dbe424a6c8d9c53af8fed375200737d9",
          "sha1": "1931fc7cea96cb20cb3924f80756782014a628cf",
          "md5": "5008798857671eecb81da6a17cab8588"
        }
      ]
    }
  ]
}
