{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "discord",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "discord-v145.jar",
          "url": "discord-v145.jar",
          "size": 15193,
          "sha512": "8258a13ead288fa988e5fc7fa32c08253fea0e634c18df30767b9f3cfc50ac173ea2a4a6aac4473e255cb43dc5dc2d04e112fe614af4c4d46ec412cc9f7c0c5b",
          "sha256": "0f5148946e3768e8884d2c178ff4d4364574da94d7dccfa3b3221b8cb7f83494",
          "sha1": "7cc4dbb408c206785cd73eab7ecb81b6c4c8a977",
          "md5": "bd5e4e7f20e8cda9abd5080f9a75e2a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-v145.jar",
          "url": "discord-v145.jar",
          "size": 15193,
          "sha512": "8258a13ead288fa988e5fc7fa32c08253fea0e634c18df30767b9f3cfc50ac173ea2a4a6aac4473e255cb43dc5dc2d04e112fe614af4c4d46ec412cc9f7c0c5b",
          "sha256": "0f5148946e3768e8884d2c178ff4d4364574da94d7dccfa3b3221b8cb7f83494",
          "sha1": "7cc4dbb408c206785cd73eab7ecb81b6c4c8a977",
          "md5": "bd5e4e7f20e8cda9abd5080f9a75e2a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-v145-sources.jar",
          "url": "discord-v145-sources.jar",
          "size": 4401,
          "sha512": "6d393d8ca9e658bdefac7d4ae33fb8f12bd6ece774a14356696f742082b41dd0e792f3a12c25b562996f61e7ea4f5a4c89e3625d38bf9703f838471bc94b90ad",
          "sha256": "dbc87f05bac2ccf34659692a0fe1c5e2bd5e8807b564b812b8d3da0f705e72eb",
          "sha1": "2b5ed1fe288dfc8adfd4ec137724aaccc2144d77",
          "md5": "0b2f377087bbf53168ea38f3ce4439f7"
        }
      ]
    }
  ]
}
