{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken",
    "module": "discord",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "discord-v145.jar",
          "url": "discord-v145.jar",
          "size": 15193,
          "sha512": "5e5f02b1ae022ce5fe970d9772bbfae13b67101df1911aaad66d94eb67c5bfe4fc6c61ae52178dddeec226da8757f9c7873db50a6d6171036cbdb95da854eefc",
          "sha256": "1d4d09a9855205214352b41838070c8d8db9975f47325b6e7afa43ed3de77de1",
          "sha1": "53643433ae86c6882b9c7d04f573d9abc21d2b73",
          "md5": "25a417d19412ef71deacc555c043c0c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-v145.jar",
          "url": "discord-v145.jar",
          "size": 15193,
          "sha512": "5e5f02b1ae022ce5fe970d9772bbfae13b67101df1911aaad66d94eb67c5bfe4fc6c61ae52178dddeec226da8757f9c7873db50a6d6171036cbdb95da854eefc",
          "sha256": "1d4d09a9855205214352b41838070c8d8db9975f47325b6e7afa43ed3de77de1",
          "sha1": "53643433ae86c6882b9c7d04f573d9abc21d2b73",
          "md5": "25a417d19412ef71deacc555c043c0c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "discord-v145-sources.jar",
          "url": "discord-v145-sources.jar",
          "size": 4401,
          "sha512": "fcb9fb8d3ce422e418234d53473b36de866c01399b48e0d71220ce4b57c155f07caf1f2300b05e468d97d451dfd76437f3992e29601dd924085ca72ec72761ea",
          "sha256": "76e4f397fab3d87d4b0bcb6f7e6740758c9c6d4c12730ecf20a1e609d2f28bc7",
          "sha1": "ac66e3ce63ca77eafd07801d3dc537d591c6cc8b",
          "md5": "01afeac53da1b2c81940c11c44d21161"
        }
      ]
    }
  ]
}
