{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "arcnet",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "arcnet-v145.1.jar",
          "url": "arcnet-v145.1.jar",
          "size": 52604,
          "sha512": "238cb78f13ecdc5fe3ebe162a9519826511c494a800101b3b5d95feb713489b0bc1262637cf6fdd3e127d14ac7570f00968267432d86a067469834f10c1df4e1",
          "sha256": "c4eb208f8ae0b25de0f11cbbedb34c7e9dd65e49a6bffad7d291036b853c31f8",
          "sha1": "eac0138ab18e3fea4bc691b2615e97dae15f9cea",
          "md5": "d399ce11d008958956e76a13b91cee09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arcnet-v145.1.jar",
          "url": "arcnet-v145.1.jar",
          "size": 52604,
          "sha512": "238cb78f13ecdc5fe3ebe162a9519826511c494a800101b3b5d95feb713489b0bc1262637cf6fdd3e127d14ac7570f00968267432d86a067469834f10c1df4e1",
          "sha256": "c4eb208f8ae0b25de0f11cbbedb34c7e9dd65e49a6bffad7d291036b853c31f8",
          "sha1": "eac0138ab18e3fea4bc691b2615e97dae15f9cea",
          "md5": "d399ce11d008958956e76a13b91cee09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arcnet-v145.1-sources.jar",
          "url": "arcnet-v145.1-sources.jar",
          "size": 28594,
          "sha512": "d805cddb495d5e40423d1449c2d517b9c5435740599dbb4ea52d0122d8d7d9a385ab9cd5e8bb07075eeb905272988aeea34cbbd4bc71ebec062f85287c6bb2aa",
          "sha256": "1513d19267ca28ac06be479a4f3a83f3b12afe421df35185890595ae11cc3844",
          "sha1": "b7f274872b9946a4605b837be77c446dba5cbfdc",
          "md5": "047a805ec1c8fc2286ac8ca858994bd5"
        }
      ]
    }
  ]
}
