{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "fx",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fx-v145.jar",
          "url": "fx-v145.jar",
          "size": 62586,
          "sha512": "407cb4ca81f2f02533543693a0004a29cacdf8f59f4870a6a1653f763c78ee1b015792c35d70d08e81d7f345fa9845ed74fee4d07296364078cee3d8097cf913",
          "sha256": "42d23eac7fa1907b368afb789ca387ad29a63d080c4bfc2ce9f7d3a4b2a2ddf1",
          "sha1": "1706f4db8ef1f6fc22152586fe4a6a32f85a23c2",
          "md5": "0a0f3dd632d1f07abe6d8744d1fde185"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fx-v145.jar",
          "url": "fx-v145.jar",
          "size": 62586,
          "sha512": "407cb4ca81f2f02533543693a0004a29cacdf8f59f4870a6a1653f763c78ee1b015792c35d70d08e81d7f345fa9845ed74fee4d07296364078cee3d8097cf913",
          "sha256": "42d23eac7fa1907b368afb789ca387ad29a63d080c4bfc2ce9f7d3a4b2a2ddf1",
          "sha1": "1706f4db8ef1f6fc22152586fe4a6a32f85a23c2",
          "md5": "0a0f3dd632d1f07abe6d8744d1fde185"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fx-v145-sources.jar",
          "url": "fx-v145-sources.jar",
          "size": 40350,
          "sha512": "7caa077252c1db8beb8b9597044f951318de0069b61fb63af3872a55cc3233539ea6e5ff8109450493ae778bfb6366ab8ba45b185a37c2e0a1f3da34d75b8b91",
          "sha256": "4a15763a73581c18f310e2bcab6053a3fc3a7a47dade9c465fd13b85a5a1d5e6",
          "sha1": "9692e8845952191ac489fc678aee366b6b64186a",
          "md5": "d245ddc9edc06c148df1c6ce6374bf1b"
        }
      ]
    }
  ]
}
