{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-ios",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-ios-v145.1.jar",
          "url": "natives-freetype-ios-v145.1.jar",
          "size": 2203198,
          "sha512": "6863d33fe0503293f7ef3a9d1cb03e80e5df6d89e9b10810ffb28054a09c51f96736a3d6d40dcc57db747244b57d460b00a904f6a2bb537e92e1cd337da54d3e",
          "sha256": "bfd0ef2a58582321da716c7b0ec40da68e0c00521289d69331aed73d050454a0",
          "sha1": "6e0f228a86d43a45aa3f19baf034820897961918",
          "md5": "76c8687d14d5ee3dcdcebc3794328116"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-ios-v145.1.jar",
          "url": "natives-freetype-ios-v145.1.jar",
          "size": 2203198,
          "sha512": "6863d33fe0503293f7ef3a9d1cb03e80e5df6d89e9b10810ffb28054a09c51f96736a3d6d40dcc57db747244b57d460b00a904f6a2bb537e92e1cd337da54d3e",
          "sha256": "bfd0ef2a58582321da716c7b0ec40da68e0c00521289d69331aed73d050454a0",
          "sha1": "6e0f228a86d43a45aa3f19baf034820897961918",
          "md5": "76c8687d14d5ee3dcdcebc3794328116"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-ios-v145.1-sources.jar",
          "url": "natives-freetype-ios-v145.1-sources.jar",
          "size": 2203198,
          "sha512": "1c3a5b698bce740b8559ec89ea60ce224d614ede8b35dd252df1616e91d97001829683906a501db17697190ee5cbdd0037d0af50cff72f8484ec5949dee638fa",
          "sha256": "b3f744293d5fb32a3e0fa6911b587fb0c5ead454db512a1cd02ea505602b9521",
          "sha1": "01ca2021e4abab1b95b63188fc61964b2f1627e1",
          "md5": "8e51f39b9dc23e41fb949e0d441a4698"
        }
      ]
    }
  ]
}
