{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.19"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v145.1.jar",
          "url": "backend-robovm-v145.1.jar",
          "size": 52462,
          "sha512": "b6b8d4cb23c8a29245b618517f01853802132fd20f378fab197676e375784f803f5074872ae780e1835633a014f4a8d141a0351d07b327602aec70e2febb480c",
          "sha256": "9fd67ef209fcf3a8e443c1fb491b182ca8d47369e78dde7c1e450aa8e6f69f2c",
          "sha1": "259510dc92b90cdcf32503d3514833046f18fe6b",
          "md5": "71a9e61ed99e155c263b5c165e234258"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.19"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v145.1.jar",
          "url": "backend-robovm-v145.1.jar",
          "size": 52462,
          "sha512": "b6b8d4cb23c8a29245b618517f01853802132fd20f378fab197676e375784f803f5074872ae780e1835633a014f4a8d141a0351d07b327602aec70e2febb480c",
          "sha256": "9fd67ef209fcf3a8e443c1fb491b182ca8d47369e78dde7c1e450aa8e6f69f2c",
          "sha1": "259510dc92b90cdcf32503d3514833046f18fe6b",
          "md5": "71a9e61ed99e155c263b5c165e234258"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v145.1-sources.jar",
          "url": "backend-robovm-v145.1-sources.jar",
          "size": 24659,
          "sha512": "a2ae398beafeba488fe96c7dc0f954723c32efc3d1e6529a040efd78d123a295cd50c38733ebcac75283bb3dacc153819fa855ebe8be1f7b23fc250412ea4138",
          "sha256": "bf186c469deb9637b6d95346b746b95b18b5650eb3a2d7048dd79656d4de4602",
          "sha1": "a44588922c9fba6200eececbe8ea9cf86b867725",
          "md5": "b72fb9a6898ea514c1409edd8dfba255"
        }
      ]
    }
  ]
}
