{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.19"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v145.1.jar",
          "url": "backend-robovm-v145.1.jar",
          "size": 52462,
          "sha512": "add5bdc73f1ce3abce368aa2b729012158bc8ea6bde37d911e973d7d912254c58fd2c1ec0ec89144682bcc724eb26ac2dccb74fc62371a2bdb6410137a667c35",
          "sha256": "229ae69afa468f1ffd330e1f215acc496b9d39e06ae28ade5ed202e7163056a6",
          "sha1": "1e4aed6561c2b2e52f94351f3ae5a50a161bb638",
          "md5": "86a45502ff07a946b46302ce9e565a3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.19"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v145.1.jar",
          "url": "backend-robovm-v145.1.jar",
          "size": 52462,
          "sha512": "add5bdc73f1ce3abce368aa2b729012158bc8ea6bde37d911e973d7d912254c58fd2c1ec0ec89144682bcc724eb26ac2dccb74fc62371a2bdb6410137a667c35",
          "sha256": "229ae69afa468f1ffd330e1f215acc496b9d39e06ae28ade5ed202e7163056a6",
          "sha1": "1e4aed6561c2b2e52f94351f3ae5a50a161bb638",
          "md5": "86a45502ff07a946b46302ce9e565a3a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v145.1-sources.jar",
          "url": "backend-robovm-v145.1-sources.jar",
          "size": 24659,
          "sha512": "d92ad14113ad1dde1c847c08cdd4aa7c865b76d31c2e81b1078c8e108eeabb7f4487c03a1c7f08d87e97aeb8f35b4cfbeee6ea996f0274d46ddb01bbcb81c82b",
          "sha256": "5f8f7ba04ab40e62d4d7d1a8172d85d14819e2f038e7684c783f3d0e2c327b51",
          "sha1": "f3d3bfd3b3e659c9ddefa93c2363c88a7e3dcfba",
          "md5": "ce60a693555caf646d999ea6d2bc9c7b"
        }
      ]
    }
  ]
}
