{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken",
    "module": "natives-box2d-ios",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v145.jar",
          "url": "natives-box2d-ios-v145.jar",
          "size": 2384392,
          "sha512": "99af41f4a5d59bb1ac6648ce72d1259485df8e2f87f6d493e818aafd311d76ea88feaad34a4cea942bda03e80d78223cbc9dedd87a650b3223b0b64c7d0fabd2",
          "sha256": "123ba8fd161afa165dcc293ddd531331b59b9366cf8328da26336cf3aac24549",
          "sha1": "b7b21fec4ac1a06de6e2fd8c6c8db3ea6d59a626",
          "md5": "a8008106a9dcafa212b3905fceb51c1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v145.jar",
          "url": "natives-box2d-ios-v145.jar",
          "size": 2384392,
          "sha512": "99af41f4a5d59bb1ac6648ce72d1259485df8e2f87f6d493e818aafd311d76ea88feaad34a4cea942bda03e80d78223cbc9dedd87a650b3223b0b64c7d0fabd2",
          "sha256": "123ba8fd161afa165dcc293ddd531331b59b9366cf8328da26336cf3aac24549",
          "sha1": "b7b21fec4ac1a06de6e2fd8c6c8db3ea6d59a626",
          "md5": "a8008106a9dcafa212b3905fceb51c1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v145-sources.jar",
          "url": "natives-box2d-ios-v145-sources.jar",
          "size": 2384392,
          "sha512": "85d7b6ffa9bb53d35abd0388980eb4ece42f7cf13830bb8eee8f2fdf0e0d7cfaffa703651e0eb378c0331d95a759794ba1e315634cc4b55711d1eb9a19ff7bdd",
          "sha256": "abdbd9c07b47b4354b8a36161f72a3b77cb9587c74bf9b33b174a9dcd62025f5",
          "sha1": "4eda3a345838daaf8e44d1067e447cea5c0f3ded",
          "md5": "1992a9a87d47c7009d367d29a24f532a"
        }
      ]
    }
  ]
}
