{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-sdl",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-sdl-v145.1.jar",
          "url": "backend-sdl-v145.1.jar",
          "size": 3750876,
          "sha512": "e0dd92efbf0f236e42f4504a541a6bb771c226fc75bffc4c3c4a697409d4f4e3ac85948ff6a24a37fc3995afccc51b04ea6330042d860230b19fa8aff1ce4cac",
          "sha256": "1a4f99cfa1c32816bf1f4239d5542013ffd936e22b53234d6bf286509cfc1e24",
          "sha1": "b96c50acf7b4602a37e625624dd1042a27ee38ea",
          "md5": "abd0c0a55caab0c06be5c37c524e03cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v145.1.jar",
          "url": "backend-sdl-v145.1.jar",
          "size": 3750876,
          "sha512": "e0dd92efbf0f236e42f4504a541a6bb771c226fc75bffc4c3c4a697409d4f4e3ac85948ff6a24a37fc3995afccc51b04ea6330042d860230b19fa8aff1ce4cac",
          "sha256": "1a4f99cfa1c32816bf1f4239d5542013ffd936e22b53234d6bf286509cfc1e24",
          "sha1": "b96c50acf7b4602a37e625624dd1042a27ee38ea",
          "md5": "abd0c0a55caab0c06be5c37c524e03cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-sdl-v145.1-sources.jar",
          "url": "backend-sdl-v145.1-sources.jar",
          "size": 3731433,
          "sha512": "0a5d066ee6699e69392e096862151eeabe2380cecb0d2c3ab7bc48b0351d51664d2028a941caf5356ad49ae7c9a18e2832d9a79e050ae6bcfcc095047275aad0",
          "sha256": "38d00b3b5d6eed6cd829376220d764e9606e6fbdc312f9cc7da3642902bd5828",
          "sha1": "c1dca8c68e7f7066ab6d8c085769de62288b232e",
          "md5": "76c776a4074c1c186090d799cb78b00b"
        }
      ]
    }
  ]
}
