{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "extensions",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "extensions-v145.jar",
          "url": "extensions-v145.jar",
          "size": 261,
          "sha512": "0273cb8ac574ac63d35c5eae24ce40ca4769ffc45ec3d8745df9f2596a54deaf81b30d2c1148ee1e64d476802e21653fe2c775c9c15770d8e58b983c31956c64",
          "sha256": "841dbba2718dd95e7887cfb684441b251a6f4939ea2384dc7f22cc03bed3e202",
          "sha1": "547e910bb9772e3bce44173a0e341bf37c0f527a",
          "md5": "9eade2a64149d490ee541acea63067b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-v145.jar",
          "url": "extensions-v145.jar",
          "size": 261,
          "sha512": "0273cb8ac574ac63d35c5eae24ce40ca4769ffc45ec3d8745df9f2596a54deaf81b30d2c1148ee1e64d476802e21653fe2c775c9c15770d8e58b983c31956c64",
          "sha256": "841dbba2718dd95e7887cfb684441b251a6f4939ea2384dc7f22cc03bed3e202",
          "sha1": "547e910bb9772e3bce44173a0e341bf37c0f527a",
          "md5": "9eade2a64149d490ee541acea63067b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-v145-sources.jar",
          "url": "extensions-v145-sources.jar",
          "size": 261,
          "sha512": "0273cb8ac574ac63d35c5eae24ce40ca4769ffc45ec3d8745df9f2596a54deaf81b30d2c1148ee1e64d476802e21653fe2c775c9c15770d8e58b983c31956c64",
          "sha256": "841dbba2718dd95e7887cfb684441b251a6f4939ea2384dc7f22cc03bed3e202",
          "sha1": "547e910bb9772e3bce44173a0e341bf37c0f527a",
          "md5": "9eade2a64149d490ee541acea63067b1"
        }
      ]
    }
  ]
}
