{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "recorder",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "recorder-v145.1.jar",
          "url": "recorder-v145.1.jar",
          "size": 5599,
          "sha512": "18f885a9dbea0e9b3d135e77d15add0ea4e0e9b43bedc25c87028addb4a89e40dcbadcb501340bfec6a34dbc7396ffd7793918d3cac12eb78af100928719a34f",
          "sha256": "d2e324237b0039db3b1162aef52e7751e9795abb8bae8a8d176a3166033b3692",
          "sha1": "562624a5768d5df3f2b806bb5c6bdb71b205bf01",
          "md5": "98a06ba4783444354ceaa9f5533b9c98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recorder-v145.1.jar",
          "url": "recorder-v145.1.jar",
          "size": 5599,
          "sha512": "18f885a9dbea0e9b3d135e77d15add0ea4e0e9b43bedc25c87028addb4a89e40dcbadcb501340bfec6a34dbc7396ffd7793918d3cac12eb78af100928719a34f",
          "sha256": "d2e324237b0039db3b1162aef52e7751e9795abb8bae8a8d176a3166033b3692",
          "sha1": "562624a5768d5df3f2b806bb5c6bdb71b205bf01",
          "md5": "98a06ba4783444354ceaa9f5533b9c98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recorder-v145.1-sources.jar",
          "url": "recorder-v145.1-sources.jar",
          "size": 2819,
          "sha512": "f31bd679127b9741ba53d6242c351757a72f3a6e727ab0f7ef5beb9174a2eac6d49ddf90acb89510184a365c4c4672b2889d7b9243523df145364eee8b984e7a",
          "sha256": "cbad3474383ca009ffa3bdabbe1f6690ecec7496a40bde01015b8534d3c7df53",
          "sha1": "aa40283e52688289defb33b8cd809b95aca96a0e",
          "md5": "cf21caeaa72c568650b0b3d8b5f4b1d8"
        }
      ]
    }
  ]
}
