{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "profiling",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "profiling-v145.1.jar",
          "url": "profiling-v145.1.jar",
          "size": 23501,
          "sha512": "c5349b11b7de3d97934b8d15df4d0eaa00e27633f29621d98d53e05bbeeea6b8c25bc5014eca1de9b9e1d979f3abb929b93b7c2a8ccfe147cee89e29ad063e1a",
          "sha256": "b056c37a08847cc84b2bf55ba145386eca0b8da651e9f9dc277e5868fc9a1e59",
          "sha1": "e8ed3d9ef25e0b1c5033c465e7eea0ae09162fe4",
          "md5": "e51dc32d9b74c18dc0e7ce0408bd7eb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profiling-v145.1.jar",
          "url": "profiling-v145.1.jar",
          "size": 23501,
          "sha512": "c5349b11b7de3d97934b8d15df4d0eaa00e27633f29621d98d53e05bbeeea6b8c25bc5014eca1de9b9e1d979f3abb929b93b7c2a8ccfe147cee89e29ad063e1a",
          "sha256": "b056c37a08847cc84b2bf55ba145386eca0b8da651e9f9dc277e5868fc9a1e59",
          "sha1": "e8ed3d9ef25e0b1c5033c465e7eea0ae09162fe4",
          "md5": "e51dc32d9b74c18dc0e7ce0408bd7eb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profiling-v145.1-sources.jar",
          "url": "profiling-v145.1-sources.jar",
          "size": 11159,
          "sha512": "9359bd335a47f33c217ff64103727dea0696bf02a0df31613abd57c4b2d52d06cf8434cc879ea248a41c0da7c77e901f07e4dbd510bcc4cbdaf3177848c1d68b",
          "sha256": "9298ff4af9a9ff5dfdb213bd26e9639d63a1c894b36b3e1bae479c732ccca717",
          "sha1": "a06c554b74e24ac9f179088b47ea43f9e87985f7",
          "md5": "fe4519274f2a9f8742f82ee01759fedc"
        }
      ]
    }
  ]
}
