{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-v145.1.jar",
          "url": "natives-v145.1.jar",
          "size": 261,
          "sha512": "9b83018dde984564e213cd5acddc86a1a9a83da545b01314e1f15ffb23d893b2514a2452d44bdb6b2692f6e1aa8deae6d716ce76563aa5c09d191c37fc62c7db",
          "sha256": "208f33563792974254dc94184aac2656d6440be77339098b1620429cd240fcec",
          "sha1": "6e315477f497bb999607f7cc90a8a37183d74fc7",
          "md5": "acfc8ed55d39faa73875598382aa4a43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-v145.1.jar",
          "url": "natives-v145.1.jar",
          "size": 261,
          "sha512": "9b83018dde984564e213cd5acddc86a1a9a83da545b01314e1f15ffb23d893b2514a2452d44bdb6b2692f6e1aa8deae6d716ce76563aa5c09d191c37fc62c7db",
          "sha256": "208f33563792974254dc94184aac2656d6440be77339098b1620429cd240fcec",
          "sha1": "6e315477f497bb999607f7cc90a8a37183d74fc7",
          "md5": "acfc8ed55d39faa73875598382aa4a43"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-v145.1-sources.jar",
          "url": "natives-v145.1-sources.jar",
          "size": 261,
          "sha512": "9b83018dde984564e213cd5acddc86a1a9a83da545b01314e1f15ffb23d893b2514a2452d44bdb6b2692f6e1aa8deae6d716ce76563aa5c09d191c37fc62c7db",
          "sha256": "208f33563792974254dc94184aac2656d6440be77339098b1620429cd240fcec",
          "sha1": "6e315477f497bb999607f7cc90a8a37183d74fc7",
          "md5": "acfc8ed55d39faa73875598382aa4a43"
        }
      ]
    }
  ]
}
