{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v147",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v147.jar",
          "url": "natives-box2d-android-v147.jar",
          "size": 411485,
          "sha512": "50c6657a1b7c29b50e3d498f1384bf5dd8529db1ebd61e206bf6dee61838cf3ec8510581876888c6d6c876d270de3699db3c6061a8b7d29e6c1da67098ce01ba",
          "sha256": "811685ee17dcdd7ec142479aa2282dca1a117e2641df64dbf268e82fbdb401a7",
          "sha1": "5b2e291eeab1b94a7fdfdb98d9b593a6e8d64aa9",
          "md5": "224387a8e27e82a3b22020174e856ac3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v147.jar",
          "url": "natives-box2d-android-v147.jar",
          "size": 411485,
          "sha512": "50c6657a1b7c29b50e3d498f1384bf5dd8529db1ebd61e206bf6dee61838cf3ec8510581876888c6d6c876d270de3699db3c6061a8b7d29e6c1da67098ce01ba",
          "sha256": "811685ee17dcdd7ec142479aa2282dca1a117e2641df64dbf268e82fbdb401a7",
          "sha1": "5b2e291eeab1b94a7fdfdb98d9b593a6e8d64aa9",
          "md5": "224387a8e27e82a3b22020174e856ac3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v147-sources.jar",
          "url": "natives-box2d-android-v147-sources.jar",
          "size": 411485,
          "sha512": "a03d84b411973a2ca9b20fb548e26e11f3d43a29de9f4caddf9a03490118b84bd45549026d8529cb08391586d7f3597e49b64643c4acfbec1ccb039f52f6b04c",
          "sha256": "fddeb77e24ad2bd12020dfe9dd5f2be31b91f5b69c2088aabc43eda35347ffba",
          "sha1": "b6bda87583d1fd25811df0a1f895b2f288a1f170",
          "md5": "7f8848c4c28e81e10c23dbbe5bce2d67"
        }
      ]
    }
  ]
}
