{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "fx",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fx-v145.1.jar",
          "url": "fx-v145.1.jar",
          "size": 62586,
          "sha512": "44259ff14535bc70e25f66d9ec03e70f87edc0d0e45ebcee3004469f6e1eb3f0c4a770083eb5c29659fc2bedc0f04716c8c1560bbdd5c75041e54e908d772e31",
          "sha256": "2fd32909582a2bf212b97b30a890eb86965c5d92021633c18b2785521ceffeed",
          "sha1": "2110f16716048647bd13e0ed5bfcc8d1c848c776",
          "md5": "8ccf7d5584b475cb89f86025a8a3d3d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fx-v145.1.jar",
          "url": "fx-v145.1.jar",
          "size": 62586,
          "sha512": "44259ff14535bc70e25f66d9ec03e70f87edc0d0e45ebcee3004469f6e1eb3f0c4a770083eb5c29659fc2bedc0f04716c8c1560bbdd5c75041e54e908d772e31",
          "sha256": "2fd32909582a2bf212b97b30a890eb86965c5d92021633c18b2785521ceffeed",
          "sha1": "2110f16716048647bd13e0ed5bfcc8d1c848c776",
          "md5": "8ccf7d5584b475cb89f86025a8a3d3d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fx-v145.1-sources.jar",
          "url": "fx-v145.1-sources.jar",
          "size": 40350,
          "sha512": "5dc3db261bde0700b39f96081cfcd61937445b692170c9938d547dfea249ce6b414fc00da9c69f144ca70ffe8c9d73c7d17c64ae507e921663e8c32a03d59821",
          "sha256": "d72ad4d100cc025674b15aee355318c91a3bcf624bc678fa424db763b81c107f",
          "sha1": "8f131fa2a397e5e8148e1d8d1b2e53c01693ea98",
          "md5": "fbded7ce76abcb23e2535c59849c16d4"
        }
      ]
    }
  ]
}
