{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "arc-core",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "arc-core-v145.1.jar",
          "url": "arc-core-v145.1.jar",
          "size": 1235470,
          "sha512": "4224c3259dca8773002f0daf1d69c4eee83ad8400719fa8b4c83acd54d04d7ac15857cce5c7f9d737215ffc178aa019e5777bc43cbed448057ff7f4acbb85f5c",
          "sha256": "611bd5ba7ffe33b0bd0cfcb78252ecb5fb11f160e2fe931792ec91a0dbee9ef5",
          "sha1": "2ca8788be0b1e340b070f491bf4297d24cef599f",
          "md5": "413b0c85ac052a6dcc2b1686ae88bfda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arc-core-v145.1.jar",
          "url": "arc-core-v145.1.jar",
          "size": 1235470,
          "sha512": "4224c3259dca8773002f0daf1d69c4eee83ad8400719fa8b4c83acd54d04d7ac15857cce5c7f9d737215ffc178aa019e5777bc43cbed448057ff7f4acbb85f5c",
          "sha256": "611bd5ba7ffe33b0bd0cfcb78252ecb5fb11f160e2fe931792ec91a0dbee9ef5",
          "sha1": "2ca8788be0b1e340b070f491bf4297d24cef599f",
          "md5": "413b0c85ac052a6dcc2b1686ae88bfda"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arc-core-v145.1-sources.jar",
          "url": "arc-core-v145.1-sources.jar",
          "size": 692693,
          "sha512": "a46804819a258d2df730993bcedea5765bf5f7c0a6161d99dedb01f471a9a0b5c8aa9581ef80468a921f3e242f56a10d9147eed96a7ae39bf0004dd5b9c9b593",
          "sha256": "a093410d3ea68bf5afa7148eeacf652496e411756356ce81417f6b464ba93c06",
          "sha1": "827b2ae362b6d196e4663134b4d6348f1c5bf0ff",
          "md5": "ce1c9389baa43f43420117dba4addcfe"
        }
      ]
    }
  ]
}
