{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-android",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-android-v145.jar",
          "url": "natives-android-v145.jar",
          "size": 1119476,
          "sha512": "949a3c29317f3e5afc75791224691c867a955baaf9f0dd27e2fb24a5a893b7a5d7dfec85fe099c3aa4b2b4196d5b90d1fc8adccad19e6bed4790126f2ba4176a",
          "sha256": "7cb84bfdb4f6f6be98e6717f762c81f11bcd0cf5e676aa454b67a54b5d2396c3",
          "sha1": "64fdfc4ebe487bef494cf69226e97858a44413a3",
          "md5": "607ea536b2441c2766686af5af8728df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-android-v145.jar",
          "url": "natives-android-v145.jar",
          "size": 1119476,
          "sha512": "949a3c29317f3e5afc75791224691c867a955baaf9f0dd27e2fb24a5a893b7a5d7dfec85fe099c3aa4b2b4196d5b90d1fc8adccad19e6bed4790126f2ba4176a",
          "sha256": "7cb84bfdb4f6f6be98e6717f762c81f11bcd0cf5e676aa454b67a54b5d2396c3",
          "sha1": "64fdfc4ebe487bef494cf69226e97858a44413a3",
          "md5": "607ea536b2441c2766686af5af8728df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-android-v145-sources.jar",
          "url": "natives-android-v145-sources.jar",
          "size": 1119476,
          "sha512": "04277ce95b8038231d43e4cc9ef5e2dc5b5919fe72efbff72c4cf78c688764fad1ca35e6d90990a794a07df6436fa4d068a705f2f9dccadfdc912798fb613acd",
          "sha256": "359e3679cfb85cc6233dc3459abeb6eae66804cf72dd03c81c749e30d6eb8f25",
          "sha1": "e4c74cd93d02d78f38fd631af385289b6be2fae8",
          "md5": "78d65ea32a843cb3543991dd3650c489"
        }
      ]
    }
  ]
}
