{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "tiled",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiled-v145.1.jar",
          "url": "tiled-v145.1.jar",
          "size": 42985,
          "sha512": "9b289d9807d7fdc80bd3cd84f56ce7b74dd3f34428dee60d6c9783af2c9ac50774f8eb6fcb8f70d48525470fd165b93d57aaded324ae636945b64e385693bd10",
          "sha256": "751116ba483363e4fcafac3073a7361a99eb60487e49b702330dd806bdf134a3",
          "sha1": "4a432cb2683c655debe08a2cfedc162e2e96fba9",
          "md5": "1f70f3c2765d9d7fdf1aea87380e55df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v145.1.jar",
          "url": "tiled-v145.1.jar",
          "size": 42985,
          "sha512": "9b289d9807d7fdc80bd3cd84f56ce7b74dd3f34428dee60d6c9783af2c9ac50774f8eb6fcb8f70d48525470fd165b93d57aaded324ae636945b64e385693bd10",
          "sha256": "751116ba483363e4fcafac3073a7361a99eb60487e49b702330dd806bdf134a3",
          "sha1": "4a432cb2683c655debe08a2cfedc162e2e96fba9",
          "md5": "1f70f3c2765d9d7fdf1aea87380e55df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiled-v145.1-sources.jar",
          "url": "tiled-v145.1-sources.jar",
          "size": 23367,
          "sha512": "3481f8368fb416cc4db1ddca4a00f32f06e7ab74c1466ce47c872bded676b56091fffe429b62cbd8c4cb0ac51fee3122f6d5f9501a4164d159118188ab0da3a1",
          "sha256": "d4aa4e65b629644e71428f51f83915c1374056bd3f2d3d6f2704fb80de29383f",
          "sha1": "4714bf5467798abd97f84dfbff175a33d8f9c80d",
          "md5": "114ab904e015d05c5526b906eaca0e4b"
        }
      ]
    }
  ]
}
