{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-desktop",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v145.jar",
          "url": "natives-box2d-desktop-v145.jar",
          "size": 512159,
          "sha512": "09e8b6936c938180bcc284136329a739c0e07f37a492d956bb8427497522ce5d3f0ea0953227af9400d2f2656a8e0ea9ac191e84c85f5009ead64cee457199a0",
          "sha256": "9274ece844118d6919f014b025e1318f49002029f742bb91db9495a019ef9070",
          "sha1": "2a7e3c1a2c57240b47085ea2fffbd9e71628c3ad",
          "md5": "b79b534aa0ad135721a529d9cecd6176"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v145.jar",
          "url": "natives-box2d-desktop-v145.jar",
          "size": 512159,
          "sha512": "09e8b6936c938180bcc284136329a739c0e07f37a492d956bb8427497522ce5d3f0ea0953227af9400d2f2656a8e0ea9ac191e84c85f5009ead64cee457199a0",
          "sha256": "9274ece844118d6919f014b025e1318f49002029f742bb91db9495a019ef9070",
          "sha1": "2a7e3c1a2c57240b47085ea2fffbd9e71628c3ad",
          "md5": "b79b534aa0ad135721a529d9cecd6176"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v145-sources.jar",
          "url": "natives-box2d-desktop-v145-sources.jar",
          "size": 512159,
          "sha512": "e8a54d4abd108b8e09fca1d2bee5c5c980cce8e73181357696af06049cb7ac86688af827e12c3f17aee19404b24991586cbdfb0c02d2ac560d0d18283299218c",
          "sha256": "6680e2241b89f02f4d27c42758118da0ba5b3d859a56a69fea72a33fafcbc6ec",
          "sha1": "85d3f24930598cef03ed1128678e17891eb91a91",
          "md5": "9d0af2b1257b31789163bfde6de9b3e9"
        }
      ]
    }
  ]
}
