{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-android",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-android-v145.1.jar",
          "url": "natives-freetype-android-v145.1.jar",
          "size": 945221,
          "sha512": "2e5b8e95a5db1a67b3a49fb2531b7bd695c10d4532e567eb912308faba6528eda0363f1b635a759c2402862ea0affec31f30813a3158c6d7563c584ede911acb",
          "sha256": "b35560715fe6bd3d82c57cbdd0074194c051b2bf281ad967cad8e8d256abe239",
          "sha1": "fdfbf0de6470c174d39d9a64531c4fe30a55661a",
          "md5": "dd110311dd8ab9488b98403bc984f526"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-android-v145.1.jar",
          "url": "natives-freetype-android-v145.1.jar",
          "size": 945221,
          "sha512": "2e5b8e95a5db1a67b3a49fb2531b7bd695c10d4532e567eb912308faba6528eda0363f1b635a759c2402862ea0affec31f30813a3158c6d7563c584ede911acb",
          "sha256": "b35560715fe6bd3d82c57cbdd0074194c051b2bf281ad967cad8e8d256abe239",
          "sha1": "fdfbf0de6470c174d39d9a64531c4fe30a55661a",
          "md5": "dd110311dd8ab9488b98403bc984f526"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-android-v145.1-sources.jar",
          "url": "natives-freetype-android-v145.1-sources.jar",
          "size": 945221,
          "sha512": "579d24525a1f0eac693d2d5dd385a080b17435bf95871f2f1a05e93c07012241a2ba05cee2cd68c6be72b81c148443d72452ff07bbf2da777823f96486b96681",
          "sha256": "3aec0e039fb93233f616855bc441d875d093d6b22baca4e8d55a37b3edf0fa14",
          "sha1": "50b1d07fe400626ab525cd3c63774ce2308884a4",
          "md5": "2b4f75c292a1bc6569878491a02fd671"
        }
      ]
    }
  ]
}
