{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken",
    "module": "natives-desktop",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-desktop-v145.jar",
          "url": "natives-desktop-v145.jar",
          "size": 1687632,
          "sha512": "f47ca386b28f259168954231b609f623afd4d8b603e2e85ab376406d8f846eed517276f53acda4887212020f02b7ea85f36cbaddc5328429750ed21c954447ae",
          "sha256": "810d3b9c30ea7855a18671bdcdf90da48801f4b8dbc0ab5d8affa8d7bccf5e69",
          "sha1": "40a1cc5c61c66088debfa3aeca5c0c6e4e8af592",
          "md5": "47a7d214fe7bd22e03c9da8d0bba9e9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-desktop-v145.jar",
          "url": "natives-desktop-v145.jar",
          "size": 1687632,
          "sha512": "f47ca386b28f259168954231b609f623afd4d8b603e2e85ab376406d8f846eed517276f53acda4887212020f02b7ea85f36cbaddc5328429750ed21c954447ae",
          "sha256": "810d3b9c30ea7855a18671bdcdf90da48801f4b8dbc0ab5d8affa8d7bccf5e69",
          "sha1": "40a1cc5c61c66088debfa3aeca5c0c6e4e8af592",
          "md5": "47a7d214fe7bd22e03c9da8d0bba9e9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-desktop-v145-sources.jar",
          "url": "natives-desktop-v145-sources.jar",
          "size": 1687632,
          "sha512": "fd50cf51e98efefb79a18fcd24cc729e7f0f7e314ac48b07e1f5758c59922c8b0e3bd760787e2f7e174cc7ffcf6ce59b9fd3ef6858f592a026df6fa632374366",
          "sha256": "01822f59b443e1bcadf30cb218ec5648171c6c5d1a7b92f4945e2e24e3680298",
          "sha1": "6a56fd286ede9c260362575e78dea10998142b89",
          "md5": "7aab88be4273be4ebe311f9ed8836c48"
        }
      ]
    }
  ]
}
