{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-desktop",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-desktop-v145.jar",
          "url": "natives-desktop-v145.jar",
          "size": 1687632,
          "sha512": "17083a6488778bfefd6c28e4a47e13395806a8e9f85deeab24b887cde5fcdded1902574ff8e58996e65b70147ea368dbfbf65dd804c455037ee4d5cfc7266639",
          "sha256": "622d8bbf7abac88329a88960925e5799c61152791f11882e5667b3dab2a9a636",
          "sha1": "31c6279be282d8d4499055e52b6e11211d7c9cc2",
          "md5": "8ea7f165d0a18897960d96cd66976bab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-desktop-v145.jar",
          "url": "natives-desktop-v145.jar",
          "size": 1687632,
          "sha512": "17083a6488778bfefd6c28e4a47e13395806a8e9f85deeab24b887cde5fcdded1902574ff8e58996e65b70147ea368dbfbf65dd804c455037ee4d5cfc7266639",
          "sha256": "622d8bbf7abac88329a88960925e5799c61152791f11882e5667b3dab2a9a636",
          "sha1": "31c6279be282d8d4499055e52b6e11211d7c9cc2",
          "md5": "8ea7f165d0a18897960d96cd66976bab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-desktop-v145-sources.jar",
          "url": "natives-desktop-v145-sources.jar",
          "size": 1687632,
          "sha512": "1d12114e8c35824ee6c7795e2d93111e005d9ae7da76c393b0ce49e36464937c1d29b5bf92c30312761bdf2bc90f8fb1415e989a5a5be7e8a780bcf86af30b3d",
          "sha256": "38f8dd3548610096b944be6fd676708fd8a3df6959a21a0dc908c7efc0f38c3c",
          "sha1": "8cb3b33de2f2de7756146c860b7cbc9c29640f14",
          "md5": "6ba386e6a36a825d8ee0cce241f0cf7f"
        }
      ]
    }
  ]
}
