{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-ios",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-ios-v145.1.jar",
          "url": "natives-ios-v145.1.jar",
          "size": 4964339,
          "sha512": "63a0d8633f8490f3f5db170913ecc97598d4d886bcf51824f007ef886f22b9316ec9d33b98b4c6d7a548b8c450872bcb224ef666d35dbd5701861c0f50affed8",
          "sha256": "b10030999e016f423453b5254cb62994b3e59a32d3918f7ecf0e26af3d223f68",
          "sha1": "ac4cc7eb5217e4e898cba15bdef97580dbadd6eb",
          "md5": "f586a5a3bcd4b3a7484b9dde5b6b8f16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-ios-v145.1.jar",
          "url": "natives-ios-v145.1.jar",
          "size": 4964339,
          "sha512": "63a0d8633f8490f3f5db170913ecc97598d4d886bcf51824f007ef886f22b9316ec9d33b98b4c6d7a548b8c450872bcb224ef666d35dbd5701861c0f50affed8",
          "sha256": "b10030999e016f423453b5254cb62994b3e59a32d3918f7ecf0e26af3d223f68",
          "sha1": "ac4cc7eb5217e4e898cba15bdef97580dbadd6eb",
          "md5": "f586a5a3bcd4b3a7484b9dde5b6b8f16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-ios-v145.1-sources.jar",
          "url": "natives-ios-v145.1-sources.jar",
          "size": 4964339,
          "sha512": "370779dd53ffff31ea16cfbf8e536afb9687e23a76e2db214968610c56652e04beabb7537fec007df1c76c27eb601523d8a5ac3f45c4053ec4d75cc0dd4d955e",
          "sha256": "5bae991d96245f4fc564e5da70ae57f21203811c03342f4e170cef894ea9aca3",
          "sha1": "c03308f3e20c5e6bcd39246357dd331626570003",
          "md5": "c7fb7dc42c8f2454fdd5338a5b02d8a6"
        }
      ]
    }
  ]
}
