{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "server",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "server-v145.1.jar",
          "url": "server-v145.1.jar",
          "size": 32811,
          "sha512": "b6f15a11fb8a42928d51c9645468aa40f6735c5ff456578f6604f64cfe97707fb017f4b662d8e87f065278f1bc8b419489286d9f0716bf9b528a8d66820482e9",
          "sha256": "5e640f6f7be698074330a78a1da291aa3cd07f002bc082e516fad93eb27cb081",
          "sha1": "0a2d708d2e0d962c47b48c295b1902b1b16c5ea0",
          "md5": "316aa0202f013247f4901b81e628f5e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v145.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "backend-headless",
          "version": {
            "requires": "v145.1"
          }
        }
      ],
      "files": [
        {
          "name": "server-v145.1.jar",
          "url": "server-v145.1.jar",
          "size": 32811,
          "sha512": "b6f15a11fb8a42928d51c9645468aa40f6735c5ff456578f6604f64cfe97707fb017f4b662d8e87f065278f1bc8b419489286d9f0716bf9b528a8d66820482e9",
          "sha256": "5e640f6f7be698074330a78a1da291aa3cd07f002bc082e516fad93eb27cb081",
          "sha1": "0a2d708d2e0d962c47b48c295b1902b1b16c5ea0",
          "md5": "316aa0202f013247f4901b81e628f5e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "server-v145.1-sources.jar",
          "url": "server-v145.1-sources.jar",
          "size": 12293,
          "sha512": "0187d3f59f6636fa77d23e94a434adbe8663202f9c135f03bfac2c56a17ca76e56def0405a75da213b88d33915b4ac76963b0f074a8c3eaa0f1415787e373e47",
          "sha256": "d75adec798d7c8f9632dc4e8584ff95edf2c2f3233a9ba7bb515b8612c6490a2",
          "sha1": "a8aca5fda6c5efb5cf8e415dfd95328cc2e998a1",
          "md5": "72c5a28cb23e39a43f5123adabd336aa"
        }
      ]
    }
  ]
}
