{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "core",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v145.jar",
          "url": "core-v145.jar",
          "size": 4836133,
          "sha512": "d38cf82b8805ab605ee7cc38916e854580b487d2c3832091e12158fee78bbbcab36b5f702254d9573a0a9cbef6669b279b85e2c7361f9491830960efd2c22587",
          "sha256": "0e072e65fb007ba7aa29e69feea9a7cbf731d3b30e4d9adf59adaa3a275fe7d6",
          "sha1": "3b015dd5fd966153474545a74137ba9b951148c1",
          "md5": "920e944e3c5520032463a191a757bfe0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v145.jar",
          "url": "core-v145.jar",
          "size": 4836133,
          "sha512": "d38cf82b8805ab605ee7cc38916e854580b487d2c3832091e12158fee78bbbcab36b5f702254d9573a0a9cbef6669b279b85e2c7361f9491830960efd2c22587",
          "sha256": "0e072e65fb007ba7aa29e69feea9a7cbf731d3b30e4d9adf59adaa3a275fe7d6",
          "sha1": "3b015dd5fd966153474545a74137ba9b951148c1",
          "md5": "920e944e3c5520032463a191a757bfe0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v145-sources.jar",
          "url": "core-v145-sources.jar",
          "size": 1291200,
          "sha512": "006a7abdddea93832cfc47f6f66fb5bad5a956aa2c1c5c7902791d843a3a2854125fdf1fa9f7b8d81a4a72e44612d7dfafa93dd6d3fe03df496137207f0e7fdd",
          "sha256": "90b345befa1dc4dcf57a9c0a77cb02f21af911efe3cc34d39d62a06952fdd172",
          "sha1": "5090583fe2e24bb3d1f1ac27f167e229eaa4929b",
          "md5": "a35c5b8c747e24ff4a0dfbc328500bb6"
        }
      ]
    }
  ]
}
