{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-ios",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-ios-v145.jar",
          "url": "natives-freetype-ios-v145.jar",
          "size": 2203198,
          "sha512": "d1a48d2469d1422cb2dbac212d754b9f16f8c9ff89bc1708658ca2d0c99329062f74d7ce9ef1bc34967858f0b2e80cb3fb5e2107b336f406769f77bf77100860",
          "sha256": "e2735e86e66bcf8000574102c022766b8789ef9e48d0095307a02a0f814c4e00",
          "sha1": "9620232206ebadcc808a9a586ea4f3c2a3bf22ff",
          "md5": "5da216e257ea410915386118ac520de3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-ios-v145.jar",
          "url": "natives-freetype-ios-v145.jar",
          "size": 2203198,
          "sha512": "d1a48d2469d1422cb2dbac212d754b9f16f8c9ff89bc1708658ca2d0c99329062f74d7ce9ef1bc34967858f0b2e80cb3fb5e2107b336f406769f77bf77100860",
          "sha256": "e2735e86e66bcf8000574102c022766b8789ef9e48d0095307a02a0f814c4e00",
          "sha1": "9620232206ebadcc808a9a586ea4f3c2a3bf22ff",
          "md5": "5da216e257ea410915386118ac520de3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-ios-v145-sources.jar",
          "url": "natives-freetype-ios-v145-sources.jar",
          "size": 2203198,
          "sha512": "c5e3c3d471301e90e648679d44b10e8ce69632b87aaa51f2c1f716afe7c16170a80df2183e957c944e8f2ed1805c89d82c60766ca1e0146245da898299e3b1a7",
          "sha256": "66824792d0d4c248981e18a286a446f9388ba74171ea4813d3c5d8c21235da6e",
          "sha1": "d8155ff6f1e99cde552dc118c037dd7421f93776",
          "md5": "212b7c850891626c4de6e4b831d450d4"
        }
      ]
    }
  ]
}
