{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "packer",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packer-v145.1.jar",
          "url": "packer-v145.1.jar",
          "size": 52591,
          "sha512": "0d84868f77112046390860e7c651eae9ec92d1c6e079eae900e05891dc1c8534da0c68b043df64c358aca51d453a5d104d743bf23886b9fef4ee669214c79d5a",
          "sha256": "0d2e7cee13c56d3ed391454ea93cbd7b156211ee2beb0fecfd7dba5cdbe0c43d",
          "sha1": "3a3839bbe91c70cedeee8233191a577e31af9bf0",
          "md5": "055527f8523fc11add5c40efc50ae129"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packer-v145.1.jar",
          "url": "packer-v145.1.jar",
          "size": 52591,
          "sha512": "0d84868f77112046390860e7c651eae9ec92d1c6e079eae900e05891dc1c8534da0c68b043df64c358aca51d453a5d104d743bf23886b9fef4ee669214c79d5a",
          "sha256": "0d2e7cee13c56d3ed391454ea93cbd7b156211ee2beb0fecfd7dba5cdbe0c43d",
          "sha1": "3a3839bbe91c70cedeee8233191a577e31af9bf0",
          "md5": "055527f8523fc11add5c40efc50ae129"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packer-v145.1-sources.jar",
          "url": "packer-v145.1-sources.jar",
          "size": 24208,
          "sha512": "6ce873bde8e0a8a4e94d435b7b68b0b78bd9bd9f1623ef6ef16ad0645ce4801991e64a2fcae64f1c55fe75c0ae266f28a8e464a3c4eaca3d95f18d481396ac47",
          "sha256": "2843636568ac7dd0447482515c037a55e387c077bd8dcc526b9ede16b33c5ec3",
          "sha1": "4c58bb94266f6cd1aa5d179465ccd1da8bdca6fd",
          "md5": "d88d536bad68599f002132d19ced0aa9"
        }
      ]
    }
  ]
}
