{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v145.jar",
          "url": "natives-freetype-desktop-v145.jar",
          "size": 1098026,
          "sha512": "46bf9404a2bd6a65844d7aea7beccbfdbb8d352191f6e498b4387d914f7a40f251b88ed79b50c4f891f22c32cd6d1513e84061bac9b04037d93bef021f6fa49b",
          "sha256": "d1ff2576ef7731882e9dd36b26a359e6ac46d35c9b9e7885ac2a24b92aac3cb3",
          "sha1": "ab6b43f88be8c6cc95e66b2d3c75c88eaebf6cd9",
          "md5": "6acc5f80aa88e92661c9c7bb03825755"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v145.jar",
          "url": "natives-freetype-desktop-v145.jar",
          "size": 1098026,
          "sha512": "46bf9404a2bd6a65844d7aea7beccbfdbb8d352191f6e498b4387d914f7a40f251b88ed79b50c4f891f22c32cd6d1513e84061bac9b04037d93bef021f6fa49b",
          "sha256": "d1ff2576ef7731882e9dd36b26a359e6ac46d35c9b9e7885ac2a24b92aac3cb3",
          "sha1": "ab6b43f88be8c6cc95e66b2d3c75c88eaebf6cd9",
          "md5": "6acc5f80aa88e92661c9c7bb03825755"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v145-sources.jar",
          "url": "natives-freetype-desktop-v145-sources.jar",
          "size": 1098026,
          "sha512": "5cb002183b42fe15dd63bdd575bcd32a89ddfd3754e26cb675e2fea482d8f005125bd8f76b3144a3463afaa89fd686fe2e2133ad275b2c8f959923e6675171e9",
          "sha256": "13f3f9bb2e3cab17a7c7e508a6bf5a9a906f55215591ee034d625f0cc3636e8f",
          "sha1": "4a5fa21ac59a88fb6f8804f06b42cb3a61ad6abb",
          "md5": "ea2907b762467034557495d31ba04b97"
        }
      ]
    }
  ]
}
