{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "extensions",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "extensions-v145.1.jar",
          "url": "extensions-v145.1.jar",
          "size": 261,
          "sha512": "5ee34dbc52d2fc9bc88495e0d27fa9e0c10c7e83c676deffe6cdd568daa2e0b2ee50fd353b46fd835132c09be3e422b9813ee8b4d9fc9b55562f6da134e300b4",
          "sha256": "6876728fa4d466909c446696deebf59e65a0b819bac144a1f7ddae2b9f6b06e5",
          "sha1": "1add9cab05813bad230ec9144715a7db6e915722",
          "md5": "8f36f4238cd11ec22cd8f9fc28da594f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-v145.1.jar",
          "url": "extensions-v145.1.jar",
          "size": 261,
          "sha512": "5ee34dbc52d2fc9bc88495e0d27fa9e0c10c7e83c676deffe6cdd568daa2e0b2ee50fd353b46fd835132c09be3e422b9813ee8b4d9fc9b55562f6da134e300b4",
          "sha256": "6876728fa4d466909c446696deebf59e65a0b819bac144a1f7ddae2b9f6b06e5",
          "sha1": "1add9cab05813bad230ec9144715a7db6e915722",
          "md5": "8f36f4238cd11ec22cd8f9fc28da594f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-v145.1-sources.jar",
          "url": "extensions-v145.1-sources.jar",
          "size": 261,
          "sha512": "5ee34dbc52d2fc9bc88495e0d27fa9e0c10c7e83c676deffe6cdd568daa2e0b2ee50fd353b46fd835132c09be3e422b9813ee8b4d9fc9b55562f6da134e300b4",
          "sha256": "6876728fa4d466909c446696deebf59e65a0b819bac144a1f7ddae2b9f6b06e5",
          "sha1": "1add9cab05813bad230ec9144715a7db6e915722",
          "md5": "8f36f4238cd11ec22cd8f9fc28da594f"
        }
      ]
    }
  ]
}
