{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "freetype",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "freetype-v145.jar",
          "url": "freetype-v145.jar",
          "size": 34423,
          "sha512": "3c4ef3f794edb5361de7cc1e05e9381df93fb9054ead1e936540a6f98998c14eb5e30c2ef85d7317af82b42b9bdea661c918cf556e55d3faeed177a8642843f2",
          "sha256": "3b499cb9e57bb180ae2e3e05a8bf81c692f5edb398d788c6cd2308bdc3269c29",
          "sha1": "da293a50a424f9a57165ec6a9380eaa429f0f11a",
          "md5": "f743aebde52bd32eb067cd27ed393f83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "freetype-v145.jar",
          "url": "freetype-v145.jar",
          "size": 34423,
          "sha512": "3c4ef3f794edb5361de7cc1e05e9381df93fb9054ead1e936540a6f98998c14eb5e30c2ef85d7317af82b42b9bdea661c918cf556e55d3faeed177a8642843f2",
          "sha256": "3b499cb9e57bb180ae2e3e05a8bf81c692f5edb398d788c6cd2308bdc3269c29",
          "sha1": "da293a50a424f9a57165ec6a9380eaa429f0f11a",
          "md5": "f743aebde52bd32eb067cd27ed393f83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "freetype-v145-sources.jar",
          "url": "freetype-v145-sources.jar",
          "size": 16375,
          "sha512": "81437a59e65e5d9c8595c9ec8eee15cee8a33e3994fd5cc2d709fbbc789ce813d4fe191742c101236f507750d170dc4948ccc316ba8889b69a195e78cc2ca7be",
          "sha256": "3291e9f3399a9bec2756747a404ed8b60c5c5916440f831d1c18ec83530ae26e",
          "sha1": "4dd84eec8cdab7ae54651926999c1c441fa7c7fc",
          "md5": "ce72d0fbf2b0178960badb42bd3dfa39"
        }
      ]
    }
  ]
}
