{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "g3d",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "g3d-v145.1.jar",
          "url": "g3d-v145.1.jar",
          "size": 45478,
          "sha512": "8065f78ac4fee56499c4294b803746a839c2d7fcb3e1d06eeaedae97320982b4b84c3b0c9e3dff60a601124327e8da3fdf0110e232fbf75b3c0f56fa91909bb0",
          "sha256": "deeb20122d59620db79a0d6cab974f1d1dde0a1d66c2cb6ebe43d76e54d43841",
          "sha1": "5655c59d5abd8c81b5a4f193b6c02148fec00b5b",
          "md5": "1decff914ab2f6389c32067edd748d9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v145.1.jar",
          "url": "g3d-v145.1.jar",
          "size": 45478,
          "sha512": "8065f78ac4fee56499c4294b803746a839c2d7fcb3e1d06eeaedae97320982b4b84c3b0c9e3dff60a601124327e8da3fdf0110e232fbf75b3c0f56fa91909bb0",
          "sha256": "deeb20122d59620db79a0d6cab974f1d1dde0a1d66c2cb6ebe43d76e54d43841",
          "sha1": "5655c59d5abd8c81b5a4f193b6c02148fec00b5b",
          "md5": "1decff914ab2f6389c32067edd748d9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v145.1-sources.jar",
          "url": "g3d-v145.1-sources.jar",
          "size": 35268,
          "sha512": "65b207636f4e9398cd2a152fb7307eed5bf36f255d4d81b1d24b6d54ed2ad023b9ad7381d37a6d226252b1d3c91194e89242407d3ec64bfec61734d9274a3a8d",
          "sha256": "2d61d1d4bb38c029e25598137b262287caf110321b1f12d53d7524d93582feb1",
          "sha1": "900fdbbc644cada6ad20f00c42fe014c455b0247",
          "md5": "eb981a85de059c6f88f60d2549149e13"
        }
      ]
    }
  ]
}
