{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v146",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v146.jar",
          "url": "natives-freetype-desktop-v146.jar",
          "size": 1098026,
          "sha512": "1e25c66ec64990144cebe60510a60b5cec05631323c7e5b6a98d2ce1a45b0b316365e90465966f9a9310fd2de4584e5fb068b0b81d2b8803b8ceeec30a45cbeb",
          "sha256": "6ffc50f0ca103ad23b251b59d9551a72915c20f6743b5a19a30708084cbe1686",
          "sha1": "0b77e85a681324a79fdb95f68a58f719d4f8b66c",
          "md5": "aae908dce25f10ea1b37541f787c952a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v146.jar",
          "url": "natives-freetype-desktop-v146.jar",
          "size": 1098026,
          "sha512": "1e25c66ec64990144cebe60510a60b5cec05631323c7e5b6a98d2ce1a45b0b316365e90465966f9a9310fd2de4584e5fb068b0b81d2b8803b8ceeec30a45cbeb",
          "sha256": "6ffc50f0ca103ad23b251b59d9551a72915c20f6743b5a19a30708084cbe1686",
          "sha1": "0b77e85a681324a79fdb95f68a58f719d4f8b66c",
          "md5": "aae908dce25f10ea1b37541f787c952a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v146-sources.jar",
          "url": "natives-freetype-desktop-v146-sources.jar",
          "size": 1098026,
          "sha512": "85efbde854bf63171114056f4e0e4e50f27a82ab51b09320141f6934640530f9807744e4b60d05a63a8641de33ff3bab2fd67adc7d7b87c943ecd776275795af",
          "sha256": "6ae0d0774b08eae5a087558e183e40771df5e1045afa772d1b1ab40c34f7583f",
          "sha1": "434bed45b7427f68fbe4cef12e12e90f66ef7f5c",
          "md5": "6a3500b8b52bdeacce93fd6ec10725ab"
        }
      ]
    }
  ]
}
