{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v145.1.jar",
          "url": "natives-box2d-android-v145.1.jar",
          "size": 411485,
          "sha512": "f097397b7822434d7fd2c2a9510e0d620740404a4f9d92ce691461e9374fd0e2f77bec48ec0d6358c15d0ba84e6cb6cf6a4af3f47895c7766402b2312c008a0a",
          "sha256": "bcb617833e68b2fa28d443a73cf813b7cfd6cdbc3a05299ab1072b070b551f4c",
          "sha1": "c4a7d840d3ff6c466edca28f254e1fa410e82954",
          "md5": "00bbeb53edc4e2cf4f5b46b7f46cf524"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v145.1.jar",
          "url": "natives-box2d-android-v145.1.jar",
          "size": 411485,
          "sha512": "f097397b7822434d7fd2c2a9510e0d620740404a4f9d92ce691461e9374fd0e2f77bec48ec0d6358c15d0ba84e6cb6cf6a4af3f47895c7766402b2312c008a0a",
          "sha256": "bcb617833e68b2fa28d443a73cf813b7cfd6cdbc3a05299ab1072b070b551f4c",
          "sha1": "c4a7d840d3ff6c466edca28f254e1fa410e82954",
          "md5": "00bbeb53edc4e2cf4f5b46b7f46cf524"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v145.1-sources.jar",
          "url": "natives-box2d-android-v145.1-sources.jar",
          "size": 411485,
          "sha512": "62d9bd748fb6c7a69be372ef5875aaa0670f1bd7f7dc12de8c394ca6888334da0c337055c8defcac49e17e2b87b8bc97af5e6ae2bc382ce1286960e6cf731a4e",
          "sha256": "1ca381398716d3287751b0ba4cfcc87c32a554dd66ce597329930697e4a1f4c9",
          "sha1": "e0ca9f30de667f66499caa6bcf71cc00632f4b77",
          "md5": "f3c3738fc92833f859914163cf53e2a1"
        }
      ]
    }
  ]
}
