{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "flabel",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flabel-v145.jar",
          "url": "flabel-v145.jar",
          "size": 33718,
          "sha512": "8cd795bfb8b55189b4c20f49e1849ada2c5d43c5c41772e0c944088344da7d19ff64894e82334e09f1607d8a671e8fe89bde3779eb7b9249126c049665a075bc",
          "sha256": "259818e4630629902bdaf9192f1966930d55e3df87131822fdb1814bdef8db14",
          "sha1": "d4658990554f3d06de03f2a1d464875365ecf472",
          "md5": "a66a5e4f6cd3da0800f6b8bfa9ee39b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flabel-v145.jar",
          "url": "flabel-v145.jar",
          "size": 33718,
          "sha512": "8cd795bfb8b55189b4c20f49e1849ada2c5d43c5c41772e0c944088344da7d19ff64894e82334e09f1607d8a671e8fe89bde3779eb7b9249126c049665a075bc",
          "sha256": "259818e4630629902bdaf9192f1966930d55e3df87131822fdb1814bdef8db14",
          "sha1": "d4658990554f3d06de03f2a1d464875365ecf472",
          "md5": "a66a5e4f6cd3da0800f6b8bfa9ee39b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flabel-v145-sources.jar",
          "url": "flabel-v145-sources.jar",
          "size": 20633,
          "sha512": "5195c61bed1ccf89ee78834aa3bfcd4880f43cf64902941a999a486e41b43ffee71f4d69d3eb85b13f56299f43fd5099c11aa4dc54377055bdbe16bac6c4fc7e",
          "sha256": "3d8c82abbfd9daf073ddc67fec19d06b54e277c787aa6061fbebd41bc5efdff3",
          "sha1": "858f12c97f270de2e58fa5d4cc0fe35cda008e19",
          "md5": "a1562f65a116ef4c580050cfbe35f35b"
        }
      ]
    }
  ]
}
