{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-headless",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-headless-v145.1.jar",
          "url": "backend-headless-v145.1.jar",
          "size": 4054,
          "sha512": "90c1c39a91b8e38ac26916c45b7f1bacbac403c34b1bd1b4ab30d9fcee39676c67ac8957be0742cb7bc1536a1179570ce6c04d24c013d311317c58b22e7c19cd",
          "sha256": "c89edeec68e499c253f6c0c916e4cdae44461b3eee88b9c017f45c07dd6db077",
          "sha1": "737ca5eb8e45bb3c948ad8ad81df1c7e1e3fd7c8",
          "md5": "ec82c6d16bf678a4b894bf18ca85c38a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-headless-v145.1.jar",
          "url": "backend-headless-v145.1.jar",
          "size": 4054,
          "sha512": "90c1c39a91b8e38ac26916c45b7f1bacbac403c34b1bd1b4ab30d9fcee39676c67ac8957be0742cb7bc1536a1179570ce6c04d24c013d311317c58b22e7c19cd",
          "sha256": "c89edeec68e499c253f6c0c916e4cdae44461b3eee88b9c017f45c07dd6db077",
          "sha1": "737ca5eb8e45bb3c948ad8ad81df1c7e1e3fd7c8",
          "md5": "ec82c6d16bf678a4b894bf18ca85c38a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-headless-v145.1-sources.jar",
          "url": "backend-headless-v145.1-sources.jar",
          "size": 1790,
          "sha512": "b8818a06b9841111c0cc1e0cdff1b078c2deeb3da55b01f95a984cbdbe328b56d25e8f139b3379eb2c827ce5d422a27e81f50ca3303c5e7e10f0d0b5652efe74",
          "sha256": "ca21626c6e1c84e9078928ed757c25307c9f4b99fffe8391878b45f780faa7fd",
          "sha1": "2fe8ea42ec318e5b36dc53367578348c3fabab99",
          "md5": "cacf987f4400a14bcad8c5f1a8e963e3"
        }
      ]
    }
  ]
}
