{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken",
    "module": "core",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v145.jar",
          "url": "core-v145.jar",
          "size": 4836133,
          "sha512": "d51ccc7c5fa456d1e567b4871ced3e122c8f282b9fdefa3c088a657ce370b4889a9665b235d7a62448dcabf5cb09187b946664c13756f7149b3535a5f22d89c1",
          "sha256": "cf8774d5ee3fde60d3c89b718428faf2dbc371019bac303aa4fb6af78e38c7c1",
          "sha1": "37c69ae0dda866252fc3615c02aae71329e80505",
          "md5": "c9e18e3f93ea4d09be0b8450d8e5b83f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "flabel",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "freetype",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "g3d",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "fx",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arcnet",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken",
          "module": "rhino",
          "version": {
            "requires": "73a812444ac388ac2d94013b5cadc8f70b7ea027"
          }
        }
      ],
      "files": [
        {
          "name": "core-v145.jar",
          "url": "core-v145.jar",
          "size": 4836133,
          "sha512": "d51ccc7c5fa456d1e567b4871ced3e122c8f282b9fdefa3c088a657ce370b4889a9665b235d7a62448dcabf5cb09187b946664c13756f7149b3535a5f22d89c1",
          "sha256": "cf8774d5ee3fde60d3c89b718428faf2dbc371019bac303aa4fb6af78e38c7c1",
          "sha1": "37c69ae0dda866252fc3615c02aae71329e80505",
          "md5": "c9e18e3f93ea4d09be0b8450d8e5b83f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v145-javadoc.jar",
          "url": "core-v145-javadoc.jar",
          "size": 5424086,
          "sha512": "ff02e2536f1e529726c394db867cf139b42d3008ed1e10c4ce55af1757336c49932ea7557d5f188dab1d69818dc8d3d564218eff87d1b099a03452b6e5915bef",
          "sha256": "27a018361c3e38bfb81f5fca3f01b3cab5bde7853917f7495df5401eeb989deb",
          "sha1": "afe8b99bd8822f7a0699d6126edb48ed4f1befdf",
          "md5": "08fdc13ea2fda033c2563987199fd916"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-v145-sources.jar",
          "url": "core-v145-sources.jar",
          "size": 1291200,
          "sha512": "b014801cdcedc0886ad59e6aa73db79532c1321754435d0719ad537c6f73f90e5aba4a275001d396ba8f368e4f258bbd7332aa852822088ceb70af87c1ad9fea",
          "sha256": "f1bc25c77738ec06aa3d23753f5101750df94e95d6bb0e614cc9ea7651f60bba",
          "sha1": "d8a51e8d4d482a02b19b5bb3b80d3e91f68a30d4",
          "md5": "c9c92c9d0da21c72aff9aa3c80d8fc4d"
        }
      ]
    }
  ]
}
