{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v147",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v147.jar",
          "url": "natives-freetype-desktop-v147.jar",
          "size": 1098026,
          "sha512": "73b7e1c3b9557efa26aa6b8b93abd59b7ce006dcd154033c2077d10dd831cc79a66ab2ad5aeb44cad6a80dede1cfa3c7ad5ccd474e5f6274d9ac68c9d87c6bd4",
          "sha256": "d09470cb6c20919875e9b5456b152d50f7535b2a5be04a01c8b521eda807a4f5",
          "sha1": "0e9b7a01d284d1b860e21db434546aac2ed83594",
          "md5": "adc957aab850777e8fb2193570baacba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v147.jar",
          "url": "natives-freetype-desktop-v147.jar",
          "size": 1098026,
          "sha512": "73b7e1c3b9557efa26aa6b8b93abd59b7ce006dcd154033c2077d10dd831cc79a66ab2ad5aeb44cad6a80dede1cfa3c7ad5ccd474e5f6274d9ac68c9d87c6bd4",
          "sha256": "d09470cb6c20919875e9b5456b152d50f7535b2a5be04a01c8b521eda807a4f5",
          "sha1": "0e9b7a01d284d1b860e21db434546aac2ed83594",
          "md5": "adc957aab850777e8fb2193570baacba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v147-sources.jar",
          "url": "natives-freetype-desktop-v147-sources.jar",
          "size": 1098026,
          "sha512": "60c5900fca2e8d641bb59c498520dd69bf79a064c88a111c2f3b896fb7439035131a0d45163667f382919ac8908820ce5fd2802899a0846ac0d397644cf1e0a5",
          "sha256": "1c57a4f965ddcdcf1da35eacaf4d4236932156df4c0ed200b278c4c4d82ece6c",
          "sha1": "1530983775d70696f653c289f698c86bb502c0c1",
          "md5": "44e49c2aae2b3274ae829754704e4fda"
        }
      ]
    }
  ]
}
