{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-robovm",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.19"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v145.jar",
          "url": "backend-robovm-v145.jar",
          "size": 52462,
          "sha512": "5b24ded03427341aed88a2d104be8baef1067a910a402ae9479d006fb564b0f9ea206510632398b8288494eb2c4de251c13dd2d72f988592995518009e5e1042",
          "sha256": "ef4e9bbff0fb6c6543468bce5497f0ca90ba0b48e71c427485a4d2b4b2ef2e03",
          "sha1": "25b417469bcfdfaaa16db33e4e704589a42c1ee6",
          "md5": "391d54017609980fbd8e14ea54292b24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-rt",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-objc",
          "version": {
            "requires": "2.3.19"
          }
        },
        {
          "group": "com.mobidevelop.robovm",
          "module": "robovm-cocoatouch",
          "version": {
            "requires": "2.3.19"
          }
        }
      ],
      "files": [
        {
          "name": "backend-robovm-v145.jar",
          "url": "backend-robovm-v145.jar",
          "size": 52462,
          "sha512": "5b24ded03427341aed88a2d104be8baef1067a910a402ae9479d006fb564b0f9ea206510632398b8288494eb2c4de251c13dd2d72f988592995518009e5e1042",
          "sha256": "ef4e9bbff0fb6c6543468bce5497f0ca90ba0b48e71c427485a4d2b4b2ef2e03",
          "sha1": "25b417469bcfdfaaa16db33e4e704589a42c1ee6",
          "md5": "391d54017609980fbd8e14ea54292b24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-robovm-v145-sources.jar",
          "url": "backend-robovm-v145-sources.jar",
          "size": 24659,
          "sha512": "3fa2a431831250327a33bffa10aa4a0b269fb2b80db258f3bffe240adc23815f9e5512b97699bef9887d11792112484cd16743c21c66872cc06fe0b2136e36d0",
          "sha256": "45fa8f15a0f04bc711a67b81e4e9d9357110bff715da8c74163a6c253c0a8508",
          "sha1": "9b8d127ca4527ef6d2c9a4710e4e814d7e0f755e",
          "md5": "ef87e8493c47383b2f841eff04b4b03c"
        }
      ]
    }
  ]
}
