{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-ios",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-ios-v145.jar",
          "url": "natives-ios-v145.jar",
          "size": 4964339,
          "sha512": "46b8619016d21e733e3b63e9790590682dcf3872f3bfe3bc5332340e73d3b951434a13313eedea13384b9b10d76456db3dd5f88590b989375c4c9ca2a7d57de1",
          "sha256": "597a0340612876efec52a1c2b2304ed027feb11cc1b958c5377f8da06586bc62",
          "sha1": "c4b6d1e6465aa0757621474e5a985082d76083bf",
          "md5": "66160a958079deed072871a49b1e5280"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-ios-v145.jar",
          "url": "natives-ios-v145.jar",
          "size": 4964339,
          "sha512": "46b8619016d21e733e3b63e9790590682dcf3872f3bfe3bc5332340e73d3b951434a13313eedea13384b9b10d76456db3dd5f88590b989375c4c9ca2a7d57de1",
          "sha256": "597a0340612876efec52a1c2b2304ed027feb11cc1b958c5377f8da06586bc62",
          "sha1": "c4b6d1e6465aa0757621474e5a985082d76083bf",
          "md5": "66160a958079deed072871a49b1e5280"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-ios-v145-sources.jar",
          "url": "natives-ios-v145-sources.jar",
          "size": 4964339,
          "sha512": "7105b618d60bd1b07fa95dd582b53dcf6caf43b733cb4a11f99169fe6bf37825be1509eb59c986fc6d111f996c64a808d7becb4835e88319ecd0292f4cae1016",
          "sha256": "6d47c204f41ffb7abe7aae410ac9eaed24cb0eec4e8a29975dfc0b344a9f24da",
          "sha1": "98386db2e3626a0de318011168a9e6b0f8665991",
          "md5": "b91c6231eb557e066829307a4dbd0810"
        }
      ]
    }
  ]
}
