{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-android",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-android-v145.jar",
          "url": "natives-freetype-android-v145.jar",
          "size": 945221,
          "sha512": "507a6c63642bf9a1d2874620acbc69c42ea3c6924932fa6f3bf9ae323b85cf8c5b753abfebd9aa9887f7d74e2c703e87745a862da22986621c0b664a9d521ed9",
          "sha256": "1a4a710b584017d0d367497b44088a0ac9a736aef19a6442a7c0e4b45091a4b6",
          "sha1": "44f12705f843a20227c1cf163a77e46aca5561f6",
          "md5": "88d3ac1b2f9921f3e13937ae6a92bf7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-android-v145.jar",
          "url": "natives-freetype-android-v145.jar",
          "size": 945221,
          "sha512": "507a6c63642bf9a1d2874620acbc69c42ea3c6924932fa6f3bf9ae323b85cf8c5b753abfebd9aa9887f7d74e2c703e87745a862da22986621c0b664a9d521ed9",
          "sha256": "1a4a710b584017d0d367497b44088a0ac9a736aef19a6442a7c0e4b45091a4b6",
          "sha1": "44f12705f843a20227c1cf163a77e46aca5561f6",
          "md5": "88d3ac1b2f9921f3e13937ae6a92bf7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-android-v145-sources.jar",
          "url": "natives-freetype-android-v145-sources.jar",
          "size": 945221,
          "sha512": "cb29f0881be384cf60fec325a69d4ca25a6a0ae63815753ef25cddb524a4f96d8429ed6b752197b42915e2dfd12f2f61df505d4ad53c4d889d4826bab46d3e93",
          "sha256": "2780ffb71e39613a34f2dcefe68cc4d528d13958ea4bad63c7fafb67b48152cf",
          "sha1": "09a4672791b43339013f193fbd4a4b0b05058e72",
          "md5": "688b267f22344b140e3fd5cb3183b186"
        }
      ]
    }
  ]
}
