{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "box2d",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "box2d-v145.1.jar",
          "url": "box2d-v145.1.jar",
          "size": 58093,
          "sha512": "2aa14672a6bb070d67ef6c8bece5e4e94de9e58f830bd4c81696a255457df75d7e0659376ab17ba3eb1c6023256d7cd87f2f85f614ce0d37828c139eef8fa413",
          "sha256": "41329bafbc0ae09d617396f40778593b5b793641393104b9c1572c72d9302ec3",
          "sha1": "be618770f0ddb1a27e7ee2cdf17a8f4af5b9864a",
          "md5": "0cfc57a76b7f4c54db2bd34883195c22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box2d-v145.1.jar",
          "url": "box2d-v145.1.jar",
          "size": 58093,
          "sha512": "2aa14672a6bb070d67ef6c8bece5e4e94de9e58f830bd4c81696a255457df75d7e0659376ab17ba3eb1c6023256d7cd87f2f85f614ce0d37828c139eef8fa413",
          "sha256": "41329bafbc0ae09d617396f40778593b5b793641393104b9c1572c72d9302ec3",
          "sha1": "be618770f0ddb1a27e7ee2cdf17a8f4af5b9864a",
          "md5": "0cfc57a76b7f4c54db2bd34883195c22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box2d-v145.1-sources.jar",
          "url": "box2d-v145.1-sources.jar",
          "size": 52592,
          "sha512": "901dffd8e3a86a46c61e2d1343c822bf607cebad046e8008ded4da5f45820c2d2533424893c67db9e3d883053b646467d7926e9a2933f198cbaa0a7ba773b50b",
          "sha256": "e6c6123132a37f1e8d0fcd89d382fde186c292cfe666b7cb057806a3f32b870e",
          "sha1": "cc8ccbd37a3af595a0b676c33c538d3206d37900",
          "md5": "fc2c2a933e394a46799c1653dd0419dc"
        }
      ]
    }
  ]
}
