{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-headless",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-headless-v145.jar",
          "url": "backend-headless-v145.jar",
          "size": 4054,
          "sha512": "9b87013506a51686538ec22238c24dec50ab512bd9d80634713adc34f41e82f779ab94f0dc98e0a133fbc654eed3bcd8d1ce763a43624fe1347b576abac323b0",
          "sha256": "c782075ad0ffece3e1e4867e33c9e04e6461ca4d01180378850dcbb9a177178b",
          "sha1": "d0d99789f2575c5a8a3938f74665b60265c8a28e",
          "md5": "f4b74f063b0a86da02165f031687828b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-headless-v145.jar",
          "url": "backend-headless-v145.jar",
          "size": 4054,
          "sha512": "9b87013506a51686538ec22238c24dec50ab512bd9d80634713adc34f41e82f779ab94f0dc98e0a133fbc654eed3bcd8d1ce763a43624fe1347b576abac323b0",
          "sha256": "c782075ad0ffece3e1e4867e33c9e04e6461ca4d01180378850dcbb9a177178b",
          "sha1": "d0d99789f2575c5a8a3938f74665b60265c8a28e",
          "md5": "f4b74f063b0a86da02165f031687828b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-headless-v145-sources.jar",
          "url": "backend-headless-v145-sources.jar",
          "size": 1790,
          "sha512": "f050a9abf3b8005d9084822177f6217c4fb755167c39b12a530aa9f3e572f98b0d387d86ded23a0e386cff0299c9b7ef93336bc6357bb67b24efc865baa76a86",
          "sha256": "c8bff9eca1472772246f03327e843b09c5de4d3499a69743a1f9a1fbac115588",
          "sha1": "d37eb57552cdcce17bdea27b18ad90a55e9c2d4d",
          "md5": "209320989020ff14f09c77b4b09d2a57"
        }
      ]
    }
  ]
}
