{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "arc-core",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "arc-core-v145.jar",
          "url": "arc-core-v145.jar",
          "size": 1235470,
          "sha512": "0a9e44ae55e0d668dc124ea4b02d59596959fcb67051932043c5c30be1f77e3c5f4361edd877919a264e8b2d2cb2860b96e4f9902aba40e28c49dbe6ccb238bc",
          "sha256": "8a523851a38ffbf838126838ec619ab823b670c22132aec70e29c8362558816d",
          "sha1": "1d879fff67ec999a493ad42c6866995207926b3d",
          "md5": "b6f08c56c0e3e0dbb049cfae8c22f781"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arc-core-v145.jar",
          "url": "arc-core-v145.jar",
          "size": 1235470,
          "sha512": "0a9e44ae55e0d668dc124ea4b02d59596959fcb67051932043c5c30be1f77e3c5f4361edd877919a264e8b2d2cb2860b96e4f9902aba40e28c49dbe6ccb238bc",
          "sha256": "8a523851a38ffbf838126838ec619ab823b670c22132aec70e29c8362558816d",
          "sha1": "1d879fff67ec999a493ad42c6866995207926b3d",
          "md5": "b6f08c56c0e3e0dbb049cfae8c22f781"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arc-core-v145-sources.jar",
          "url": "arc-core-v145-sources.jar",
          "size": 692693,
          "sha512": "6a3d54bcc31386bba11144d4bb94cce2422fe08603163211691be20e1538fb650305c9780c4861266263c0d724ac2d96967a5e9271d5227eb95f0fe61e58115c",
          "sha256": "bedacdbc35aacc1563d7a37d742eefa20f1039380f8fa628178b7744ceda1c71",
          "sha1": "0445aa411567cfd6e7f981676e03629ff188f1c4",
          "md5": "adf3fe493c13eed7ac8ee497e2b0efdc"
        }
      ]
    }
  ]
}
