{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "flabel",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flabel-v145.1.jar",
          "url": "flabel-v145.1.jar",
          "size": 33718,
          "sha512": "c322f7bf03ff8d174e1635aa8d459f070de0bb45a9b06cccb6c70b084210e93040ab210da225e27d3b7106cf5c62c85060d45cf622d31612e6eeda6cef5cb758",
          "sha256": "4eeed32b36ac04983efa5b57e0f6eb2a4e2af4493728da299b336bf3e9bcd748",
          "sha1": "166ead1fe9c530c47a4c00d6693c103e00cf2371",
          "md5": "9e25f41d166967b71dfc8dc6ab88416b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flabel-v145.1.jar",
          "url": "flabel-v145.1.jar",
          "size": 33718,
          "sha512": "c322f7bf03ff8d174e1635aa8d459f070de0bb45a9b06cccb6c70b084210e93040ab210da225e27d3b7106cf5c62c85060d45cf622d31612e6eeda6cef5cb758",
          "sha256": "4eeed32b36ac04983efa5b57e0f6eb2a4e2af4493728da299b336bf3e9bcd748",
          "sha1": "166ead1fe9c530c47a4c00d6693c103e00cf2371",
          "md5": "9e25f41d166967b71dfc8dc6ab88416b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flabel-v145.1-sources.jar",
          "url": "flabel-v145.1-sources.jar",
          "size": 20633,
          "sha512": "466f807b3e1c4b3d8f5f897ea16c3a9e18f09cea304a35a01d6f43807608dc687fc3597a41233312db27fed3c76f242fae9c34be733e3409fd50652e43f8eaaf",
          "sha256": "1c5c8cbd88dedb3ddbcc0f053fccd12f289880e0046d32607944edc96b0ecbdb",
          "sha1": "feb2c30f3e92453f8bc68e8573a5a294aba6b44c",
          "md5": "5d554176ff8f647665e70627387a8b4c"
        }
      ]
    }
  ]
}
