{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "flabel",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "flabel-v145.1.jar",
          "url": "flabel-v145.1.jar",
          "size": 33718,
          "sha512": "e600dc14a9d02cc7ac030ca4ec7b53610ed3d28fc1cc6ab865e4a2b251421bb0128edd54d65269919b24a6e0567b56f5f319128436fa9586f406af4bd5ebef38",
          "sha256": "c0a2976a69fff5fbc019c030c44ed794537d154c3d944ab58d455d448a55cf98",
          "sha1": "0652e4a497fa1682c87f37c9ce3501a745d0e373",
          "md5": "680c5d89ad99c7937be7be13a8c5ef09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flabel-v145.1.jar",
          "url": "flabel-v145.1.jar",
          "size": 33718,
          "sha512": "e600dc14a9d02cc7ac030ca4ec7b53610ed3d28fc1cc6ab865e4a2b251421bb0128edd54d65269919b24a6e0567b56f5f319128436fa9586f406af4bd5ebef38",
          "sha256": "c0a2976a69fff5fbc019c030c44ed794537d154c3d944ab58d455d448a55cf98",
          "sha1": "0652e4a497fa1682c87f37c9ce3501a745d0e373",
          "md5": "680c5d89ad99c7937be7be13a8c5ef09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flabel-v145.1-sources.jar",
          "url": "flabel-v145.1-sources.jar",
          "size": 20633,
          "sha512": "3f70c44462db6a6306bb80375df04cb1758c6d680ca364aa59e2680446a9ab122a006e7a4eb43365df93f4a945659171aa08766cfecada35e705f7ea121ce65b",
          "sha256": "37f58a173deb606d47bbaaba45dba7044f0b35c607d10dbcabe19bbc51ec5d76",
          "sha1": "f3f757cbec0316496fccc45375436432824d19c6",
          "md5": "4a44836fc645079a3cee92d7d320b24e"
        }
      ]
    }
  ]
}
