{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "box2d",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "box2d-v145.jar",
          "url": "box2d-v145.jar",
          "size": 58093,
          "sha512": "3d80c74ae9e5d10b6aadee2ed87e59b092c0c484fa1dc644b462153c27cbe9f8481eaef5b3ec52b9e9228667c34257a5f341c25b962a40aed97b724b91606471",
          "sha256": "1e9f2bb1896527a7420c95c92bd2eb01a47484c839a8360b03e8de8782cf7e71",
          "sha1": "aa044f9d0434a106909b253fe6d6aafe66ce4f98",
          "md5": "bdc23bfcc3fd5ac4b3f6aba91218a3e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box2d-v145.jar",
          "url": "box2d-v145.jar",
          "size": 58093,
          "sha512": "3d80c74ae9e5d10b6aadee2ed87e59b092c0c484fa1dc644b462153c27cbe9f8481eaef5b3ec52b9e9228667c34257a5f341c25b962a40aed97b724b91606471",
          "sha256": "1e9f2bb1896527a7420c95c92bd2eb01a47484c839a8360b03e8de8782cf7e71",
          "sha1": "aa044f9d0434a106909b253fe6d6aafe66ce4f98",
          "md5": "bdc23bfcc3fd5ac4b3f6aba91218a3e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "box2d-v145-sources.jar",
          "url": "box2d-v145-sources.jar",
          "size": 52592,
          "sha512": "6237646ee2a8abd5e21fb54469e30707064a56d68936044ae224a37c186827e1e7ded0e4d54ae05d822c4a7a4b2e46ba1da5767c5cd161ecbe78ff0dd7f78bc7",
          "sha256": "f9b2a249a57641bd93a1f4e213166f6ca506a5599b856fc5c6e29a4037a00cba",
          "sha1": "cf483c693d682635ca671d0755911b055fc51075",
          "md5": "2e2e1606b12d2b1b00982a9cacaf4665"
        }
      ]
    }
  ]
}
