{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backends",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backends-v145.jar",
          "url": "backends-v145.jar",
          "size": 261,
          "sha512": "6672f46dfd658be1de722c5e2a1ad5a79d54d0f07d303bed1375b9672c31fd5b4681fe8f3aa251076742374ea4fdba7797daa8e0e42ad51985024460285fe84a",
          "sha256": "b6d5b9ae2162121e849c6306c092bd61a0f4690c05e16de81f915ae7b792b5d5",
          "sha1": "c32b04225f9cc8f731fa9131be376e4b12847640",
          "md5": "2b84557a68def34058fd64aff7559b72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v145.jar",
          "url": "backends-v145.jar",
          "size": 261,
          "sha512": "6672f46dfd658be1de722c5e2a1ad5a79d54d0f07d303bed1375b9672c31fd5b4681fe8f3aa251076742374ea4fdba7797daa8e0e42ad51985024460285fe84a",
          "sha256": "b6d5b9ae2162121e849c6306c092bd61a0f4690c05e16de81f915ae7b792b5d5",
          "sha1": "c32b04225f9cc8f731fa9131be376e4b12847640",
          "md5": "2b84557a68def34058fd64aff7559b72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backends-v145-sources.jar",
          "url": "backends-v145-sources.jar",
          "size": 261,
          "sha512": "6672f46dfd658be1de722c5e2a1ad5a79d54d0f07d303bed1375b9672c31fd5b4681fe8f3aa251076742374ea4fdba7797daa8e0e42ad51985024460285fe84a",
          "sha256": "b6d5b9ae2162121e849c6306c092bd61a0f4690c05e16de81f915ae7b792b5d5",
          "sha1": "c32b04225f9cc8f731fa9131be376e4b12847640",
          "md5": "2b84557a68def34058fd64aff7559b72"
        }
      ]
    }
  ]
}
