{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-android",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-android-v145.jar",
          "url": "natives-box2d-android-v145.jar",
          "size": 411485,
          "sha512": "1cffe8fa31c72118c0cfd027c90f2e18a473b0e5e352936085b31b7084a3b2a27ef9585c2dd86ada902cbff0ab679d03ca99aeb27d92537aa36a8f8acce48d5b",
          "sha256": "226cdb8ce38f56622cc41de72df29180962906397fa3fc617d0afa8a342e2ee8",
          "sha1": "10f8fcc337cbf5e65004367d6f6c6cc060be48eb",
          "md5": "d0a704a322d793200fe06b211faf9f98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v145.jar",
          "url": "natives-box2d-android-v145.jar",
          "size": 411485,
          "sha512": "1cffe8fa31c72118c0cfd027c90f2e18a473b0e5e352936085b31b7084a3b2a27ef9585c2dd86ada902cbff0ab679d03ca99aeb27d92537aa36a8f8acce48d5b",
          "sha256": "226cdb8ce38f56622cc41de72df29180962906397fa3fc617d0afa8a342e2ee8",
          "sha1": "10f8fcc337cbf5e65004367d6f6c6cc060be48eb",
          "md5": "d0a704a322d793200fe06b211faf9f98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-android-v145-sources.jar",
          "url": "natives-box2d-android-v145-sources.jar",
          "size": 411485,
          "sha512": "fba1e98c297fd8c9603faa3a6d73c812956d2f1dfd08b7da41113a462a4b6d304296cf3e04f047258362f5966e1a4292bf3d3a70cbc6e92191939db821d8b351",
          "sha256": "6dfa14c8cb9f71c0911b8add19a4da5e6784123d320a2764d29939ba6c2b544a",
          "sha1": "a8d1bdc021c79fa0be8dbdad2b84820d94d9fc2a",
          "md5": "44ea64bdbfc8cfacbd7b8ca74b016cec"
        }
      ]
    }
  ]
}
