{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "recorder",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "recorder-v145.jar",
          "url": "recorder-v145.jar",
          "size": 5599,
          "sha512": "cbb5ef28646dd3a713b11e703c24710bf434cc085baf28d4b5e905468712adbad7fb5a1ef62f933057e98a8f43e2058c5dbda809884d153299349ce2810c3775",
          "sha256": "d825f227d2c2808acc3bc638853c03ecd9dacea04a2bb939a55c4ddc28176a7b",
          "sha1": "983817c4e3689f0abf44eddbfaf599bdb18dcb07",
          "md5": "037e72ee73a197c437f9469883a08e10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recorder-v145.jar",
          "url": "recorder-v145.jar",
          "size": 5599,
          "sha512": "cbb5ef28646dd3a713b11e703c24710bf434cc085baf28d4b5e905468712adbad7fb5a1ef62f933057e98a8f43e2058c5dbda809884d153299349ce2810c3775",
          "sha256": "d825f227d2c2808acc3bc638853c03ecd9dacea04a2bb939a55c4ddc28176a7b",
          "sha1": "983817c4e3689f0abf44eddbfaf599bdb18dcb07",
          "md5": "037e72ee73a197c437f9469883a08e10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recorder-v145-sources.jar",
          "url": "recorder-v145-sources.jar",
          "size": 2819,
          "sha512": "28e235b2839795c130ef5a1147b30fead5347da0fc0f3836cf4b065976760b3d669f314e6a23afa55c6b01994832e99739fdcfa1a8a530762400e95e583210c9",
          "sha256": "63ded6f1140922f3cc6253d63c5c826c884a39bd1042b043f5d927e4ae515aee",
          "sha1": "72b007d0c8f36fb8ed1fd7361ef242be73856264",
          "md5": "589ef2fbfc666c84eac472106662b20f"
        }
      ]
    }
  ]
}
