{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "packer",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packer-v145.jar",
          "url": "packer-v145.jar",
          "size": 52591,
          "sha512": "dc342a5f0622802df2c1fe7fb9ab5abd4dc06df8fc05749863ca8ee854040f4b60f2d4c9cc6a101b4a737f063321c0d63cd9ef980b503251ae3c01a1fe6453df",
          "sha256": "c32f7512c7a4ef56bcb7201804a69bdb2e3ee3c0f3d04ef9711ddcceb3637136",
          "sha1": "0b209e8bbd258b3cfb73f94f277c9257e8d15df4",
          "md5": "4bf17c1d2b276b3e8ba8d0da456908b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packer-v145.jar",
          "url": "packer-v145.jar",
          "size": 52591,
          "sha512": "dc342a5f0622802df2c1fe7fb9ab5abd4dc06df8fc05749863ca8ee854040f4b60f2d4c9cc6a101b4a737f063321c0d63cd9ef980b503251ae3c01a1fe6453df",
          "sha256": "c32f7512c7a4ef56bcb7201804a69bdb2e3ee3c0f3d04ef9711ddcceb3637136",
          "sha1": "0b209e8bbd258b3cfb73f94f277c9257e8d15df4",
          "md5": "4bf17c1d2b276b3e8ba8d0da456908b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packer-v145-sources.jar",
          "url": "packer-v145-sources.jar",
          "size": 24208,
          "sha512": "fcd940cf619a67572c8366f619b96704a96d46446e3776252d543a001e864b414bb4156a17ff39c2689e0fc31bec913443c98b6a8358c91fa050a7ad61b1dc19",
          "sha256": "8e198818cde3b5a0da2af5573ea01d32e672a3b28005ebe1b69b326132edc065",
          "sha1": "554fb927147323259fa33cebc3a1238b503f3456",
          "md5": "1029f35895b98e3dfd6cd295c7d86b8e"
        }
      ]
    }
  ]
}
