{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken",
    "module": "backend-android",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-android-v145.jar",
          "url": "backend-android-v145.jar",
          "size": 68308,
          "sha512": "3260c187cee11330c620f9a9d8ae92b2559aaee23821ac04ca2be09d95bccfd9cb8b60c063f5abd65d042eb23b82194db7e19386aac1742d4e2d801c3b1d1c97",
          "sha256": "28a71cf0a6b6fc9db726367bf0d894baccc38d840868bff2dfe7835e14e331ad",
          "sha1": "4d5ec022d2d41aa9ec93df0fc62ce121e55d4d34",
          "md5": "897d9ee85a176888b96e0511e49e6287"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-android-v145.jar",
          "url": "backend-android-v145.jar",
          "size": 68308,
          "sha512": "3260c187cee11330c620f9a9d8ae92b2559aaee23821ac04ca2be09d95bccfd9cb8b60c063f5abd65d042eb23b82194db7e19386aac1742d4e2d801c3b1d1c97",
          "sha256": "28a71cf0a6b6fc9db726367bf0d894baccc38d840868bff2dfe7835e14e331ad",
          "sha1": "4d5ec022d2d41aa9ec93df0fc62ce121e55d4d34",
          "md5": "897d9ee85a176888b96e0511e49e6287"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-android-v145-sources.jar",
          "url": "backend-android-v145-sources.jar",
          "size": 36097,
          "sha512": "3745216b11769d8e49cf3d43ec08c0d7700277f52a93ecc1dda21acc1fd29eec9ab1f3db61aa54143e409f1b3d877c4025f591b1b0a4eb6264a35262952f52ce",
          "sha256": "fb321b00d80e44cbc158fc03bbc14e6f03eeb9af5d9ece35c2fc2890f3b29a7f",
          "sha1": "ed26f8b7c916c99d1fa613bd18f6258285287247",
          "md5": "e17c804b9a434502b83ead5ec5cd4bcc"
        }
      ]
    }
  ]
}
