{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "backend-android",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "backend-android-v145.jar",
          "url": "backend-android-v145.jar",
          "size": 68308,
          "sha512": "fae733b88d02e1b188c78affdcad19b4ee39bbadc78bc1802cd9d5521baeffec8979b9099fe7973e175c2567ee1605ec6b39d67e7f520b5d27f779705d0e4ac5",
          "sha256": "0a91ebd32f41c151c7f99fd14ff72335bbfacc7a5e1f83a252f7d901621a513a",
          "sha1": "d842913c20df6fc26e3ed82b152c1845f72b29c0",
          "md5": "7dd5b3d5c769c06c1526c487b7feda57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-android-v145.jar",
          "url": "backend-android-v145.jar",
          "size": 68308,
          "sha512": "fae733b88d02e1b188c78affdcad19b4ee39bbadc78bc1802cd9d5521baeffec8979b9099fe7973e175c2567ee1605ec6b39d67e7f520b5d27f779705d0e4ac5",
          "sha256": "0a91ebd32f41c151c7f99fd14ff72335bbfacc7a5e1f83a252f7d901621a513a",
          "sha1": "d842913c20df6fc26e3ed82b152c1845f72b29c0",
          "md5": "7dd5b3d5c769c06c1526c487b7feda57"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "backend-android-v145-sources.jar",
          "url": "backend-android-v145-sources.jar",
          "size": 36097,
          "sha512": "48904aa47ba49216abda400cdf7655ff72c19f6535eab78c03681390046deeabbe822a8a29a75533727ef18be817aa24f7492f7447566f73f99d853fa1d9f4cf",
          "sha256": "1d5350d9e5ebddcf19f7e84191a787168cb11bcfa8cd32fe1e61141c22807fd7",
          "sha1": "82856d030df9cd3288864c1637b9900907fa39c2",
          "md5": "cce255e6adeca8ee28787b68755be9e9"
        }
      ]
    }
  ]
}
