{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-freetype-desktop",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v145.1.jar",
          "url": "natives-freetype-desktop-v145.1.jar",
          "size": 1098026,
          "sha512": "e1b4cc2bbcbf7e3b5d3b953a3ebf0850ebc04f075915dd8df1a9b25245a15aca1116eadb93735edfcdd7ed442c56ff06fb55ebfdd753f1a388ac684fa842877f",
          "sha256": "070a815c700a43781a4ce40ed8ac9a970ebfc29e438e150b1a1945dbf95f049a",
          "sha1": "2e2fa0025b0e3d925ce3cfbc18fbe77ba39d2db5",
          "md5": "eb688609b40c1cc1a3e87941b5bdb1cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v145.1.jar",
          "url": "natives-freetype-desktop-v145.1.jar",
          "size": 1098026,
          "sha512": "e1b4cc2bbcbf7e3b5d3b953a3ebf0850ebc04f075915dd8df1a9b25245a15aca1116eadb93735edfcdd7ed442c56ff06fb55ebfdd753f1a388ac684fa842877f",
          "sha256": "070a815c700a43781a4ce40ed8ac9a970ebfc29e438e150b1a1945dbf95f049a",
          "sha1": "2e2fa0025b0e3d925ce3cfbc18fbe77ba39d2db5",
          "md5": "eb688609b40c1cc1a3e87941b5bdb1cd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-freetype-desktop-v145.1-sources.jar",
          "url": "natives-freetype-desktop-v145.1-sources.jar",
          "size": 1098026,
          "sha512": "2e93c3dc7b31211103c77e5f6b063a0dd101b775da331ac71f024bbf38354333c7ab1f5c06582d75b43d10c675382a78f7422915e99586257d0d1a49185fa659",
          "sha256": "5bd1a7e389ab6f7db2ca97af6ddf116a171389ae5f2f724657a418a43fe7708f",
          "sha1": "3ad6a591b173d6d4093ba14639576c694ea77ed6",
          "md5": "fece11e4f201613328ca502ad90c7179"
        }
      ]
    }
  ]
}
