{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-ios",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v145.jar",
          "url": "natives-box2d-ios-v145.jar",
          "size": 2384392,
          "sha512": "a8519c2c0720e3074f2b74be75ec20a5fc3ca8d012d54d964807fb2c6f2d528b955280628764e77437ecc9b7ae8fe9c2f7423c4ae8c21762751924805e69119c",
          "sha256": "716d1754ba63a3de79772002b48bbebd0f799dbd21209b75e4e1a5b69559b0d9",
          "sha1": "962b37bd52ae2237c9871d489d0bfcb2bbe19a53",
          "md5": "4eae7e5d286b22de504094058f0f2a95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v145.jar",
          "url": "natives-box2d-ios-v145.jar",
          "size": 2384392,
          "sha512": "a8519c2c0720e3074f2b74be75ec20a5fc3ca8d012d54d964807fb2c6f2d528b955280628764e77437ecc9b7ae8fe9c2f7423c4ae8c21762751924805e69119c",
          "sha256": "716d1754ba63a3de79772002b48bbebd0f799dbd21209b75e4e1a5b69559b0d9",
          "sha1": "962b37bd52ae2237c9871d489d0bfcb2bbe19a53",
          "md5": "4eae7e5d286b22de504094058f0f2a95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-ios-v145-sources.jar",
          "url": "natives-box2d-ios-v145-sources.jar",
          "size": 2384392,
          "sha512": "e124ce4461679e5a8b58b44567131666c2ee9e9b1dfd71ad950e0e7d5a2e2c523fcf08ee9bb7a8ec2080a415e29f597172630da3458dbdc1fdc57928edac572a",
          "sha256": "04153e5c43bda8346eaa37ae3c34219d0ceae11259d35e16b9186ff8a3bf5021",
          "sha1": "c4cd02f8725203d05fc380619625c9378b7c7cb0",
          "md5": "f458bf0d57b046844abcfb3e56514beb"
        }
      ]
    }
  ]
}
