{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.rhino",
    "module": "unzip-sources",
    "version": "73a812444ac388ac2d94013b5cadc8f70b7ea027",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "unzip-sources-73a812444ac388ac2d94013b5cadc8f70b7ea027.jar",
          "url": "unzip-sources-73a812444ac388ac2d94013b5cadc8f70b7ea027.jar",
          "size": 938762,
          "sha512": "9b35376f94c7ba27c36b7a7c23dcf35e21316513c6ade6fe0437fa026e9de8ea784b7d0e89d0634e9c744b40a636d710c154cd5e7a9a02304db780bc93208471",
          "sha256": "3227c2a36697218cfd7888300cef4771cc125f9faa66afe355a9b5834c182699",
          "sha1": "2055545e82258c225a073d936a903b7a8faf8eb2",
          "md5": "447fb51960d631a5b410c02806aa11f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "unzip-sources-73a812444ac388ac2d94013b5cadc8f70b7ea027.jar",
          "url": "unzip-sources-73a812444ac388ac2d94013b5cadc8f70b7ea027.jar",
          "size": 938762,
          "sha512": "9b35376f94c7ba27c36b7a7c23dcf35e21316513c6ade6fe0437fa026e9de8ea784b7d0e89d0634e9c744b40a636d710c154cd5e7a9a02304db780bc93208471",
          "sha256": "3227c2a36697218cfd7888300cef4771cc125f9faa66afe355a9b5834c182699",
          "sha1": "2055545e82258c225a073d936a903b7a8faf8eb2",
          "md5": "447fb51960d631a5b410c02806aa11f8"
        }
      ]
    }
  ]
}
