{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "natives-box2d-desktop",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v145.1.jar",
          "url": "natives-box2d-desktop-v145.1.jar",
          "size": 512159,
          "sha512": "16fdc03db7b87d6457f17660fa2de983f073938789bd93f358e17cc0d68c455244dbe8b95f49fa7acb0da6ffbdb08c1aa3c37c74ed7bc5600e648a0d1f35c7ae",
          "sha256": "761bf45108679c1f93898151d677b43de7bdb3624e46827ff64f15a970c83e9d",
          "sha1": "aaa3c730583e509e19bd666422af0fa7da2402e9",
          "md5": "85b5dd421e790610ca81fb392a66dba1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v145.1.jar",
          "url": "natives-box2d-desktop-v145.1.jar",
          "size": 512159,
          "sha512": "16fdc03db7b87d6457f17660fa2de983f073938789bd93f358e17cc0d68c455244dbe8b95f49fa7acb0da6ffbdb08c1aa3c37c74ed7bc5600e648a0d1f35c7ae",
          "sha256": "761bf45108679c1f93898151d677b43de7bdb3624e46827ff64f15a970c83e9d",
          "sha1": "aaa3c730583e509e19bd666422af0fa7da2402e9",
          "md5": "85b5dd421e790610ca81fb392a66dba1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "natives-box2d-desktop-v145.1-sources.jar",
          "url": "natives-box2d-desktop-v145.1-sources.jar",
          "size": 512159,
          "sha512": "39eb849af3665ed83a36b70e9ee03b776be9192bbe239d4fdbe29f5865686db94877a2454a94fe56227622aafeb06604fd6a5c92accf9e59b98097603b4d8ac0",
          "sha256": "3d4e71ed97721eed4206c523ec6e424acb442d7a2b075b392c511ddabe7ddaee",
          "sha1": "3aa401e2e88edcefeadea2352fa4039f7fe16924",
          "md5": "d6e4b14be84233a30c4538ee34227d63"
        }
      ]
    }
  ]
}
