{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "freetype",
    "version": "v145.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "freetype-v145.1.jar",
          "url": "freetype-v145.1.jar",
          "size": 34423,
          "sha512": "57655383ca1d705f7c93c41920236434ee4d86ad0f62be97934954a85d61f800bd913853c978909d5a757051f200350c21b029ba8cc666c3f934ae6b6d7fd3d2",
          "sha256": "fe00ab69c269288a90cce59d28a813fe331068d22d38e9466eb3d53bd240c2bd",
          "sha1": "01cca8291b54305e1e7014a557e35651c7555206",
          "md5": "a61057a7bd09b8b541a11a49ab4cef94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "freetype-v145.1.jar",
          "url": "freetype-v145.1.jar",
          "size": 34423,
          "sha512": "57655383ca1d705f7c93c41920236434ee4d86ad0f62be97934954a85d61f800bd913853c978909d5a757051f200350c21b029ba8cc666c3f934ae6b6d7fd3d2",
          "sha256": "fe00ab69c269288a90cce59d28a813fe331068d22d38e9466eb3d53bd240c2bd",
          "sha1": "01cca8291b54305e1e7014a557e35651c7555206",
          "md5": "a61057a7bd09b8b541a11a49ab4cef94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "freetype-v145.1-sources.jar",
          "url": "freetype-v145.1-sources.jar",
          "size": 16375,
          "sha512": "28f87d23586e348b8ce9e238b8cb92a1e226d50ce7a732ddc86c64b8b169e118eda695732382a0ccdddad1664720b3a01d17c563d689231870285d8e23fdd358",
          "sha256": "eed64173a195f2c4472f18b318d9d9155ada209d10d2f99360a70f7dc97c5c6d",
          "sha1": "40f3e4c1b5c11e4ac093541c97542aa4a7d2dd75",
          "md5": "f9ee0d0293943ca102ab5d92008e0a2f"
        }
      ]
    }
  ]
}
