{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Mindustry",
    "module": "server",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "server-v145.jar",
          "url": "server-v145.jar",
          "size": 32811,
          "sha512": "800fad1cc3acd064f3ca6668db88e1802b8d13a130abaec6f7fce83540677db9a60cc0e2239adeee5c52b0720a634141381a1e7c3682f00864bd4dbff6dc4f15",
          "sha256": "b33d0a1e5ec1f28602d599c44c8473c06692cd9c58bb99a8b618b57494dd428e",
          "sha1": "908cde0ae37f5f59287e96c7d30bda729b9ece4e",
          "md5": "2ce37e96f7a31aeaafc2a8b3e5f93c86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v145"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "backend-headless",
          "version": {
            "requires": "v145"
          }
        }
      ],
      "files": [
        {
          "name": "server-v145.jar",
          "url": "server-v145.jar",
          "size": 32811,
          "sha512": "800fad1cc3acd064f3ca6668db88e1802b8d13a130abaec6f7fce83540677db9a60cc0e2239adeee5c52b0720a634141381a1e7c3682f00864bd4dbff6dc4f15",
          "sha256": "b33d0a1e5ec1f28602d599c44c8473c06692cd9c58bb99a8b618b57494dd428e",
          "sha1": "908cde0ae37f5f59287e96c7d30bda729b9ece4e",
          "md5": "2ce37e96f7a31aeaafc2a8b3e5f93c86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "server-v145-sources.jar",
          "url": "server-v145-sources.jar",
          "size": 12293,
          "sha512": "720272d4902d715c09b420f96501683141bf5c804fb84fa0aa6c92862e6714483d2d69e6c413589471a4a367c8f7ef7e8600d9b3d337e330e2c0a77cc1fffc9a",
          "sha256": "678a4a08f14e526f32ee511ebe832d399ac63909bd7a43276990078a8e7e0bdd",
          "sha1": "32a2c55626d7456bb1af9f66efb20074fb656cf7",
          "md5": "1448cad8c79782490fc5c5a4d38f8eab"
        }
      ]
    }
  ]
}
