{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken",
    "module": "g3d",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "g3d-v145.jar",
          "url": "g3d-v145.jar",
          "size": 45478,
          "sha512": "3cb44c968d89ee52b962a0324a14991d6663060eef44519cd5aba49a8a6c4ec8ba754afcba7a8e908cf656c778b1ff60c63a0d49fc9d2c0d04e1c3e2a3ebd5c6",
          "sha256": "8fa446fc9e2667d561b82aec93f190405171dd47e604e5bff5457f43082db42c",
          "sha1": "69df97e81d9cf1c702a51ed8460e2d8a6f05d231",
          "md5": "56dc8c478327af623c2aa4cdd5d78e83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v145.jar",
          "url": "g3d-v145.jar",
          "size": 45478,
          "sha512": "3cb44c968d89ee52b962a0324a14991d6663060eef44519cd5aba49a8a6c4ec8ba754afcba7a8e908cf656c778b1ff60c63a0d49fc9d2c0d04e1c3e2a3ebd5c6",
          "sha256": "8fa446fc9e2667d561b82aec93f190405171dd47e604e5bff5457f43082db42c",
          "sha1": "69df97e81d9cf1c702a51ed8460e2d8a6f05d231",
          "md5": "56dc8c478327af623c2aa4cdd5d78e83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v145-sources.jar",
          "url": "g3d-v145-sources.jar",
          "size": 35268,
          "sha512": "f5928ccf63833b99b83b2563f473f45751a7645ff323e287a04b343623a2e1a24cda889f21af712364f2eb320b352d4be86137b4fde23ab8b99bb2aa37e81cba",
          "sha256": "d1c655221679ee60c0be71a7d739ded8a0941b8bbaedd0469a6060d512a41d53",
          "sha1": "95478f8d71a4de431ec0eab9198e35b41785d1e8",
          "md5": "2693dd9e56cc5dce0430120e3207a654"
        }
      ]
    }
  ]
}
