{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "g3d",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "g3d-v145.jar",
          "url": "g3d-v145.jar",
          "size": 45478,
          "sha512": "0d9bba27e0f58e799804587ac246e084a35898ade413c72dff954ae3af4975662a3bbdf8eaef9eaed11f527e277e312863c4d7ae7538724e02336acc22a926b1",
          "sha256": "50a5305c7cecbdb4c7a19c761e2ec703ced2bc56836511575578b7fa0501d7ad",
          "sha1": "3003277f54622cee7052292fa46ed0d39eb81356",
          "md5": "f997ba549f4f3ad590fa392b87cfdd56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v145.jar",
          "url": "g3d-v145.jar",
          "size": 45478,
          "sha512": "0d9bba27e0f58e799804587ac246e084a35898ade413c72dff954ae3af4975662a3bbdf8eaef9eaed11f527e277e312863c4d7ae7538724e02336acc22a926b1",
          "sha256": "50a5305c7cecbdb4c7a19c761e2ec703ced2bc56836511575578b7fa0501d7ad",
          "sha1": "3003277f54622cee7052292fa46ed0d39eb81356",
          "md5": "f997ba549f4f3ad590fa392b87cfdd56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "g3d-v145-sources.jar",
          "url": "g3d-v145-sources.jar",
          "size": 35268,
          "sha512": "0cc85ff6f68fe08878a68a0b52edaef310a1edd8f5c4899c3b7f241b99275231ff76cee1ebb59204ba9d94709c82f818bae4d656d2db7ac315a5083f1c39a830",
          "sha256": "17068ea24b65760af342cf837d1d82cdcf828a3649085be38db3ec803a0d4161",
          "sha1": "c0b1cc6370dec9640c4daa694297bec276f6094e",
          "md5": "89dc54c85c8dcaf31903fdc85f990b1a"
        }
      ]
    }
  ]
}
