{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Anuken.Arc",
    "module": "arcnet",
    "version": "v145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "arcnet-v145.jar",
          "url": "arcnet-v145.jar",
          "size": 52604,
          "sha512": "95bd1071d683916da78db3d22e9d0c9f5035ae5de31fa070348eb93c4f223d4a37334be4386d9baf4ba5cd867ebf06405e585cdc7eeb2396b493de5738e50318",
          "sha256": "da7ecc09ae28eee16fff839eca8125e7bedfbcc20f2a4faed9154acd533d4c68",
          "sha1": "0adb7c4111f26863210b5195c85ec64b9c46e90f",
          "md5": "66cadd26181f8b992e01a020b2bbe9d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arcnet-v145.jar",
          "url": "arcnet-v145.jar",
          "size": 52604,
          "sha512": "95bd1071d683916da78db3d22e9d0c9f5035ae5de31fa070348eb93c4f223d4a37334be4386d9baf4ba5cd867ebf06405e585cdc7eeb2396b493de5738e50318",
          "sha256": "da7ecc09ae28eee16fff839eca8125e7bedfbcc20f2a4faed9154acd533d4c68",
          "sha1": "0adb7c4111f26863210b5195c85ec64b9c46e90f",
          "md5": "66cadd26181f8b992e01a020b2bbe9d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "arcnet-v145-sources.jar",
          "url": "arcnet-v145-sources.jar",
          "size": 28594,
          "sha512": "691bd448251df20e7a9c599d9a35caaacd51860fc09e8af22c5a0bd7b21908c1aa7a11eaec74297a9515670a185a8c26dffc6a50452ae36a64cf9942d49353d3",
          "sha256": "9b79e9a1f00f237a514d56d6fd2e8a2e1334d3611ed33ae4075103151bc4b971",
          "sha1": "c41663413ccffeceb021a39e8042bd65b559836c",
          "md5": "192ada7dd39ed8762d68edc54aec0314"
        }
      ]
    }
  ]
}
